### ISSUE TITLE
When using CurlClient in place of GuzzleClient as the HttpClient, timeouts can be frequent

### ISSUE THREAD

**Issue by KelseySheely** [infusionsoft/infusionsoft-php#100]
The CurlClient uses the CurlTransport as its XmlRpcTransport which sets the CURLOPT_TIMEOUT_MS to 5000. With large applications, that timeout is frequently reached. There is nothing in the SDK which allows you to change that option.

The default GuzzleClient works just fine. The CurlClient is completely unreliable for large applications and should not be used. I recommend either getting rid of it or using a different XmlRpcTransport which does not set the timeout or at least allows for overriding it.

**Comment by micfai** [comment]
@KelseySheely we're overriding the timeout in the CurlClient request function. Are there certain calls which you get the timeout more frequently on?

**Comment by KelseySheely** [comment]
I seemed like we were mostly getting the timeouts on calls to retrieve data such as DataService.Query, SearchService.getSavedSearchResultsAllFields.  However, our application definitely does far more calls for retrieving data than for adding or updating data, so it may be that I just didn't notice any of those calls failing.
