### ISSUE TITLE
Any docs for DataService.query?

### ISSUE THREAD

**Issue by curious-jim** [infusionsoft/infusionsoft-php#102]
> queryData: A struct containing query data

What can I use in here? Simply `where id = 1` is not enough.

How can I use `NOT`? e.g. `where id != 1`

Is there a way to use OR/AND? for example to get Contacts with tag1 and tag2?

Maybe I can use IN?

Why you don't write any docs for your product?

**Comment by micfai** [comment]
We have updated our documentation to reflect the different operations you can use in the query data.

https://developer.infusionsoft.com/docs/xml-rpc/#data-query-a-data-table
