### ISSUE TITLE
Set new contact status to Marketable via API

### ISSUE THREAD

**Issue by keyboSlice** [infusionsoft/infusionsoft-php#103]
I am creating a new contact in infusionsoft like so:

			$contact = [
				"FirstName" => $customer->first_name,
				"LastName"  => $customer->last_name,
				"StreetAddress1" => $customer->contactDetails->address_line_one,
				"StreetAddress2" => $customer->contactDetails->address_line_two,
			 	"PostalCode"	 => $customer->contactDetails->postcode,
			 	"Phone1Type"	 => "Home",
			 	"Phone1"		 => $customer->contactDetails->landline,
			 	"Phone2Type"	 => "Mobile",
			 	"Phone2"		 => $customer->contactDetails->mobile,
			 	"Email"			 => $customer->contactDetails->email,
			 	"_InitialSiteVisitDate" => $visit->format ("Y-m-d"),
			 	"_InitialSiteVisitTime" => $visit->format ("H:i"),
			 	"_AppointmentBooker"	=> "Other",
			 	"Leadsource" 	 => $customer->source->name
			];

			$contactId = $this->infusionsoft->contacts->addWithDupCheck ($contact, "Email");

This works fine, but is there some column I can pass that will make the new contact not have a "non-marketable" status? Cannot see any column name that looks appropriate, but would like to add a checkbox on my new contact form that will let the user specify that the contact is happy to receive marketing.

**Comment by micfai** [comment]
@keyboSlice There is not a column you need to specify to opt the email address in. You need to use the EmailService to opt in the email address.  https://developer.infusionsoft.com/docs/xml-rpc/#email-opt-in-an-email-address

**Comment by cliftonscott** [comment]
@micfai Does the optin need to happen before the contact is created? 

> This method only works the first time an email address opts-in.

It seems like I need to opt in the person's email address first, then look up the contact record by email address to retrieve the contactId and add their name. Is that how it should be done?

**Comment by houtbyte** [comment]
Hi, I am also unsure how to do this with the Rest API. Please answer.
