### ISSUE TITLE
Unable to "compose" PHP SDK

### ISSUE THREAD

**Issue by jimoe666** [infusionsoft/infusionsoft-php#104]
linux 4.4.49-16-default x86_64
PHP 5.5.14
Composer 1.2.1 

I downloaded that current infusionsoft-php-master, unzipped it. Tried to compose; here is the session:

$ composer require infusionsoft/php-sdk
Using version ^1.2 for infusionsoft/php-sdk
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - The requested package infusionsoft/php-sdk No version set (parsed as 1.0.0) is satisfiable by infusionsoft/php-sdk[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
Installation failed, reverting ./composer.json to its original content.

How do I resolve the problem?

**Comment by micfai** [comment]
This sounds like you are unfamiliar with how to use composer. If you download the zip and extract it, you only need to run `composer install` and not `composer require infusionsoft/php-sdk`.

you would only use require if you have an existing composer project that you want to add the sdk to.

**Comment by jimoe666** [comment]
True, I have never used composer before. I just followed the installation directions on the project page.

"composer install" worked much better.
