### ISSUE TITLE
REST Appointments Implemented?

### ISSUE THREAD

**Issue by pfeiferchristopher** [infusionsoft/infusionsoft-php#105]
Hello,

I was just going thru and creating all the code to use this packages `->tasks()` service to create Tasks for my Leads via API when I went to try `->appointments()` and noticed that the `AppointmentService` isn't even implemented.

Is there a reason for this?

**Comment by micfai** [comment]
We are still currently building out the rest endpoints so not every object has had a rest endpoint created yet.

**Comment by pfeiferchristopher** [comment]
I see, perhaps I will work on it and create a PR because this is something we want to implement and I'd rather go thru this package than handshake with the API myself. Any pointers?

**Comment by micfai** [comment]
I see what you mean. It wasn't implemented in the sdk. I'm not sure how we missed adding it to the sdk. We'll get it added ASAP.

**Comment by micfai** [comment]
To reference this in your composer file, update it to use 1.2.5-beta
