### ISSUE TITLE
How to get token 

### ISSUE THREAD

**Issue by ArifLateefShah** [infusionsoft/infusionsoft-php#106]
I am trying to add contact to infusionsoft from my website using API and its asking for token .I dont have any idea where from i can generate or get that token.
I have tried this 
$infusionsoft->requestAccessToken($_GET['code']);
but it is generating error for "Code".

Can anyone help???

**Comment by micfai** [comment]
Take a look at the samples. You need to redirect and grant access to the Infusionsoft application and then you'll be redirected back to your script with a code.

https://github.com/infusionsoft/infusionsoft-php/blob/master/samples/addWithDupCheck.php#L53

**Comment by dkaitou** [comment]
Hi @micfai 

Thank you for the answer here. 
Do you guys have any token related documentation for different use cases? 

For example:
1. For one time access software applications.  Which may not require to save the token to database.
2. For continuing access software applications. Which may need to save token to database/session and refresh that periodically.

**Comment by jakenoble** [comment]
I have the same questions, I just want to add Contacts but do not want to have to get a Token each time and authorise the application to do this.

How can I just use an API key to send data into InfusionSoft?

**Comment by pfarcasanu** [comment]
@jakenoble did you ever manage to solve this?
