### ISSUE TITLE
Getting Custom Field Database Names

### ISSUE THREAD

**Issue by pfeiferchristopher** [infusionsoft/infusionsoft-php#107]
So I've searched high and low, near and far and I still can not find a single way to get the "Backend database names" for a Infusionsoft Account, through the API.

I know where to find them in the user interface, but what I'm building is to integration with Infusionsoft so it will not be our account that's being used, and it would be cumbersome to have all our users go there, come back, and fill out a list of "database names" because they do not always match the Field's name and some times aren't 100% logical so it's impossible to code for this.

I _hope_ I am wrong, and some one will point me to the light.

**Comment by micfai** [comment]
You can get a list of custom field database names from the [DataFormField](https://developer.infusionsoft.com/docs/table-schema/) table. In the future, questions like these should be posted on our [community forum](http://community.infusionsoft.com/c/api) as issues on this repo need to be for issues with the php sdk and not the api itself.

**Comment by pfeiferchristopher** [comment]
Indeed, thank you.
