### ISSUE TITLE
vendor/autoload.php file missing.

### ISSUE THREAD

**Issue by harshitnayak45** [infusionsoft/infusionsoft-php#109]
Where i can find file vendor/autoload.php.

**Comment by harshitnayak45** [comment]
Please provide

**Comment by yugenekr** [comment]
This is a file generated by composer: https://getcomposer.org/doc/01-basic-usage.md#autoloading

**Comment by harshitnayak45** [comment]
Can you send me autoload.php code.

**Comment by yugenekr** [comment]
As I said before, it's generated by composer, so autoload.php file contents is going to depend on which libraries you include using composer package manager.

**Comment by harshitnayak45** [comment]
How can i install this on my server

**Comment by yugenekr** [comment]
This article describes installation: https://getcomposer.org/doc/00-intro.md . 
BTW, the question you've opened is not actually an infusionsoft-php issue. It's more a question of how you setup your environment.
