### ISSUE TITLE
Issue with refresh access token

### ISSUE THREAD

**Issue by harshitnayak45** [infusionsoft/infusionsoft-php#110]
Hello ,

I have successfully refreshed the access token. I have to insert the contact details to infusionsoft via cron job But i have one question Did this script successfully run and maintain the refreshing access token ? because currently i have maintain the session. I have inserted the serialize token into database and set token then refresh them with the help of session.every time a new refreshed tokens are inserted to DB. But when i run that file in private tab then its not working.  please suggest more on this

**Comment by harshitnayak45** [comment]
Also the file in public tab is not working when we close the browser.

**Comment by harshitnayak45** [comment]
hi @bigdave @chuckreynolds @andrewryno @vivin @mattmerrill 
Can you provide vendor autoload files with all dependencies in a zip file . I have tried install it using composer but not working at my side. please send me in zip file.

**Comment by ismailiiui** [comment]
Yes, I was having a similar issue and that was that after I serialize token and store it in DB, the database strips the back slash from object name Infusionsoft\Token considering it an escape character. So when I would pull the token from DB it will return as InfusionsoftToken.

I took care of that and things are fine now.
