### ISSUE TITLE
 Call to a member function getRefreshToken() on array Infusionsoft.php on line 266

### ISSUE THREAD

**Issue by ismailiiui** [infusionsoft/infusionsoft-php#112]
Why is it considering Token as an array on that line?

**Comment by ismailiiui** [comment]
Ok I found solution on my own, it looks like when we JSON decode the Token object it no longer remains Token but appears as an array. Since there is no easy way to cast array to an object in PHP, I initialized new token and then another problem arises, which was the construct data names were mismatched to the JSON decoded array. So I created another array to match the names and viola.
Here is the solution:
$temptoken = json_decode($tokentoken,true);
	$newtoken = array('access_token' =>$temptoken['accessToken'],
	'refresh_token' =>$temptoken['refreshToken'],
	'expires_in' =>$temptoken['endOfLife'] - time(),
	'extraInfo' =>$temptoken['extraInfo']);
	
	$tokentoset = new \Infusionsoft\Token($newtoken);
	// var_dump($tokentoset);
	$infusionsoft->setToken($tokentoset);

**Comment by dkaitou** [comment]
Hi @ismailiiui  

Is the value for $tokentoken on your line 1 from database ?  And that value on $tokentoken was saved from last API request ?
