### ISSUE TITLE
Uncaught Error: Call to undefined method Infusionsoft\Api\Rest\OrderService::placeOrder() 

### ISSUE THREAD

**Issue by ismailiiui** [infusionsoft/infusionsoft-php#113]
As  I am trying to add an order and I get this error

Uncaught Error: Call to undefined method Infusionsoft\Api\Rest\OrderService::placeOrder() 

As I go into the code and this function really does not exist under Rest\OrderService

but exists in \Api\OrderService

**Comment by micfai** [comment]
Correct. PlaceOrder is an xmlrpc endpoint and not a rest endpoint. In the readme it says to use `$infs->orders('xml')`  to use the xmlrpc version.

**Comment by ismailiiui** [comment]
Why does the docs tell it differently then?

https://developer.infusionsoft.com/docs/xml-rpc/#order
