### ISSUE TITLE
unauthorized 401?

### ISSUE THREAD

**Issue by ismailiiui** [infusionsoft/infusionsoft-php#114]
I am getting this fatal error when trying to add a contact

Fatal error: Uncaught Infusionsoft\Http\HttpException: fXmlRpc\Exception\HttpException: An HTTP error occurred: Unauthorized in /us/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Exception/HttpException.php:32 Stack trace: #0 /us/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Transport/HttpAdapterTransport.php(51): fXmlRpc\Exception\HttpException::httpError('Unauthorized', 401) #1 /us/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Client.php(152): fXmlRpc\Transport\HttpAdapterTransport->send('https://api.inf...', '<?xml version="...') #2 /us/vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/InfusionsoftSerializer.php(28): fXmlRpc\Client->call('ContactService....', Array) #3 /us/vendor/infusionsoft/php-sdk/src/Infusionsoft/Infusionsoft.php(406): Infusionsoft\Http\InfusionsoftSerializer->request('ContactService....', 'https://api.inf...', Array, in

**Comment by micfai** [comment]
Your token most likely expired or have an invalid token.

**Comment by ismailiiui** [comment]
Yes, the issue was that after I serialize token and store it in DB, the database strips the back slash from object name Infusionsoft\Token considering it an escape character. So when I would pull the token from DB it will return as InfusionsoftToken.

I took care of that and things are fine now.

**Comment by micfai** [comment]
I have never seen `serialize()` strip slashes on it's own. What driver are you using to access the database?
