### ISSUE TITLE
Invalid Client and Access Denied Error

### ISSUE THREAD

**Issue by sarahgregorio29** [infusionsoft/infusionsoft-php#115]
Hi I'm trying to use your sdk but I'm getting Invalid Client error:
http://i.imgur.com/AyzayXt.png

If I click Allow it will redirect to my redirect_url with this parameters:
?state=&error=access_denied&error_uri=https%3A%2F%2Fdeveloper.infusionsoft.com%2Fdocs%2Fread%2FGetting_Started_With_OAuth2&error_description=User+denied+access+to+resource

**Comment by ismailiiui** [comment]
Are you using API credentials from infusionsoft website or developer website?

If you are using API from website then its wrong, you need to use API from developer website.

**Comment by sarahgregorio29** [comment]
Ohh, how will the developer website connect to the infusionsoft website?

**Comment by ismailiiui** [comment]
You will create a developer account app and then authorize that app from infusionsoft user, just like authorize  facebook or twitter.

**Comment by sarahgregorio29** [comment]
I am inside the developer website, I don't see the client ID

**Comment by ismailiiui** [comment]
Your key is the clientid and secret is clientsecret

**Comment by sarahgregorio29** [comment]
OMG it's working now. Thank you so muuuuuuuch!

**Comment by bgpartridge** [comment]
Thanks for jumping in @ismailiiui.  @sarahgregorio29 for future reference "how to" questions like this are best addressed in the [developer/API section of our community forum](http://community.infusionsoft.com/c/api).  There you have dozens of developers and Infusionsoft personnel engaging in conversations and answering questions.  Best of luck to you!
