### ISSUE TITLE
Explanation of refresh needed

### ISSUE THREAD

**Issue by amityweb** [infusionsoft/infusionsoft-php#118]
Using the code example, I can obtain a token and save that in my database for use in the app. I can successfully add a contact, so all good so far. 

But the code examples show nothing about refreshing the token. The documentation explain it, in that I have to make a POST request etc, and pass previous refresh_tokens. All seems quite complicated compared to the simple calls in the PHP example you gave. 

Do I have to implement that myself, using REST calls, or does this code take care of it already? We can't manually refresh it everyday, the app will stop working if we don't. So we need to compare the endOfLife time to current time everytime its initiated to submit an automatic refresh and then update the token in our database. But I can see references to refreshToken methods in your code, so is it already in there? If your code takes care of refreshing already, how can I get a refreshed token when it happens to save in the database for use the next time, as we cant use sessions due to different users accessing the website. 

Hope all that makes sense!

Thanks

**Comment by micfai** [comment]
In the addWithDupCheck it shows how to refresh the token.
https://github.com/infusionsoft/infusionsoft-php/blob/master/samples/addWithDupCheck.php#L53

The easiest way to do this is to store the token serialized like we show in the sample only stored in the database instead. That way you can unserialize and set the Token like we do in the sample.
https://github.com/infusionsoft/infusionsoft-php/blob/master/samples/addWithDupCheck.php#L19

You can use `$infusionsoft->getToken()->getEndOfLife()` to grab the expiration time where you can than setup a wp_cron to refresh it.

**Comment by amityweb** [comment]
Great, I have managed to figure it out now I think, thanks a lot.
