### ISSUE TITLE
Endpoints not working? 

### ISSUE THREAD

**Issue by amityweb** [infusionsoft/infusionsoft-php#119]
Using your example for tasks, e.g. $tasks = $infusionsoft->tasks()->all();, I get the error below which implies there is no tasks method?
`Fatal error: Uncaught Error: Call to undefined method Infusionsoft\Infusionsoft::tasks()`
(I dont want tasks though, was just following the example)

My code should be working fine because contacts works OK, I can get FirstName back:
`$contacts = $infusionsoft->contacts()->load(21, array('FirstName'));`

I'm trying to list all Campaigns, but same issue as Tasks. 
```
$campaigns = $infusionsoft->campaigns();
Fatal error: Uncaught Error: Call to undefined method Infusionsoft\Infusionsoft::campaigns()
$campaigns = $infusionsoft->campaigns()->all();
Fatal error: Uncaught Error: Call to undefined method Infusionsoft\Infusionsoft::campaigns()
```

Specially my app will need to find a user by email and add a tag to them if they exist. If they dont exist, create the user and tag them. 

Oh, creating users as per your example works OK too, so I know its all working. 
`$infusionsoft->contacts->add(array('FirstName' => 'John', 'LastName' => 'Doe'));`

Where is there more documentation on how to call the end points? 

Thanks

**Comment by micfai** [comment]
What version of the sdk do you have? Tasks were added in 1.2.x and campaigns in 1.3.x

**Comment by amityweb** [comment]
I downloaded Master branch. I can see it says v 1.2.3. Is tasks in that? Don't need tasks. Guess develop branch has campaigns? Can try that tomorrow.

If there are endpoints missing is there anything we can do to implement them? Briefly saw something about hooks? Otherwise guess I could write my own curl code to call the end points direct until you add them. 

Thanks

**Comment by micfai** [comment]
If you downloaded the master branch, then everything should be in there. I just downloaded it and tested everything and they all work.

**Comment by amityweb** [comment]
Actually I installed it with composer. Would that be the 1.2 version as per the code on your documentation? 
```
{
    "require": {
        "infusionsoft/php-sdk": "1.2.*"
    }
}
```

**Comment by amityweb** [comment]
In fact, the composer file I have following the composer command is:

**Comment by amityweb** [comment]
OK got it working! You may want to update the docs on the home page...

So I originally used the following command to install it:
`composer require infusionsoft/php-sdk`
 
The generated composer.json file had this in it:
```
{
    "require": {
        "infusionsoft/php-sdk": "^1.0"
    }
}
```
So looks like version 1.0 was installed. 

Updated composer.json to the following, including allowing dev stability:
```
{
    "require": {
        "infusionsoft/php-sdk": "^1.3"
    },
    "minimum-stability": "dev"
}
```
I then ran composer update to update the package, and now my campaigns endpoint is working OK. 

So I guess your docs or package should be updated somewhere as your documentation on the home page is referencing a later version of the SDK that is not installed using composer.

**Comment by micfai** [comment]
1.3 is still currently a beta release so that is why we haven't updated the Readme yet.

**Comment by amityweb** [comment]
Sure, but the documentation includes Tasks examples which is not in the version installed using composer listed on the same page.

**Comment by micfai** [comment]
@amityweb 1.2.x has tasks  https://github.com/infusionsoft/infusionsoft-php/commit/9716cb752e75ab5d6ac050be937a6b12bb6aff0e#diff-3b8c421611fc1cfe0dc4649e182b5edcR610

**Comment by amityweb** [comment]
yes but as stated I believe 1.0 was installed, tasks was certainly not there until I updated composer.json to install a later version.
