### ISSUE TITLE
How to get actual items details, from protected array

### ISSUE THREAD

**Issue by amityweb** [infusionsoft/infusionsoft-php#120]
If I call the following I get all tasks or campaigns object
`$tasks = $infusionsoft->tasks()->all();`

but the items themselves are protected so i cant access them. Within each items:protected object are the task or campaign details in the attributes, but these are also protected. 

I cant find a method that will return the actual details as an array or object I can loop through. 

Thanks

**Comment by micfai** [comment]
The Rest API is based loosely on https://laravel.com/docs/5.1/collections . Not all methods are implemented though.

If you want to iterate through it, you can just use the $tasks variable.

```
foreach($tasks as $task){
     var_dump($task);
}
```

If you want to just dump all the tasks then you can do this `var_dump($tasks->toArray());`
