### ISSUE TITLE
GuzzleHttp\Client

### ISSUE THREAD

**Issue by limabibi** [infusionsoft/infusionsoft-php#121]
I'm trying to use the voices API and this error is appearing:

Fatal error: Class 'GuzzleHttp\Client' not found in

What do I do? Help me please

Thanks.

**Comment by micfai** [comment]
Did you run composer install?

**Comment by limabibi** [comment]
Estou usando o mesmo arquivo do exemplo. 

{
    "name": "infusionsoft/php-sdk",
    "description": "PHP SDK for the Infusionsoft",
    "keywords": [
        "infusionsoft",
        "sdk"
    ],
    "homepage": "https://developer.infusionsoft.com",
    "license": "MIT",
    "authors": [
        {
            "name": "Infusionsoft",
            "homepage": "https://developer.infusionsoft.com"
        }
    ],
    "require": {
        "php": ">=5.5",
        "ext-curl": "*",
        "guzzlehttp/guzzle": "~6.1",
        "lstrojny/fxmlrpc": "0.11",
        "egeloen/http-adapter": "~0.6",
        "psr/log": "~1.0"
    },
    "require-dev": {
        "mockery/mockery": "^0.9",
        "phpunit/phpunit": "~4",
        "squizlabs/php_codesniffer": "1.*"
    },
    "autoload": {
        "psr-0": {
            "Infusionsoft": ["src", "tests"]
        }
    }
}


**************************************
E uma outra coisa o exemplo da API de PhP é confusa, eu sou nova na area de desenvolvimento e não entendi nada dos exemplos. Por exemplo:

Eu utilizei 

$infusionsoft->contacts->add(array('FirstName' => 'John', 'LastName' => 'Doe'));

E voltou um erro falando que a função "add"  nao existe.

Poderia me enviar um exemplo adicionando os contatos?

E desculpa pelo ingles confuso, estou usando o tradutor.

**Comment by limabibi** [comment]
Hello, I was able to download all the libraries I needed for an API. But I have a new question:

$ Infusionsoft-> contacts-> add (array ('FirstName' => 'John', 'LastName' => 'Doe'));

This error appears:

Fatal error: Call to undefined method Infusionsoft \ Api \ Rest \ ContactService :: add () in

Could you help me in that case?

thanks

**Comment by micfai** [comment]
The latest version of the SDK uses rest by default for contacts. You can view can view that documentation at https://developer.infusionsoft.com/docs/rest/ 

The rest api methods are based loosely on https://laravel.com/docs/5.4/eloquent 

To create a contact using rest you do this:

```
    $email1        = new \stdClass;
    $email1->field = 'EMAIL1';
    $email1->email = 'john.doe@example.com';
    $contactData       = ['given_name' => 'John', 'family_name' => 'Doe', 'email_addresses' => [$email1]];

    $contact = $infusionsoft->contacts()->create($contactData);
```

**Comment by limabibi** [comment]
Thank you for responding.

So if I want to

Infusionsoft -> contacts -> add (array ('FirstName' => 'John', 'LastName' => 'Doe'));

I have to use request by XML-RPC?

**Comment by micfai** [comment]
You will have to specify to use XML-RPC
`$infusionsoft->contacts('xml')->add(array ('FirstName' => 'John', 'LastName' => 'Doe'));`

**Comment by limabibi** [comment]
Thank you for asking my questions.

I'm going to search XML-RPC, because I have no idea how to do it.

Sorry for any inconvenience.
As I said earlier I'm starting now in the development area.

**Comment by limabibi** [comment]
Hello,

I would like to know how I put **tags** in the contacts as soon as I create them.


I am using this command for new contact:

 $email1        = new \stdClass;
    $email1->field = 'EMAIL1';
    $email1->email = 'john.doe@example.com';
    $contactData       = ['given_name' => 'John', 'family_name' => 'Doe', 'email_addresses' => [$email1]];

    $contact = $infusionsoft->contacts()->create($contactData);



thanks

**Comment by micfai** [comment]
Once you get a response from creating the contact, you can do 
```$contact->applyTags([123,456,789]);```

Future questions can be asked on our community forums as they are getting out of scope of this issue.

http://community.infusionsoft.com/c/api

**Comment by limabibi** [comment]
Ok, thanks
