### ISSUE TITLE
Unable to update LeadSource for contact through api

### ISSUE THREAD

**Issue by coderanil** [infusionsoft/infusionsoft-php#123]
Here is my dd of data that i am passing to update contact api, but everything is updating as expected, except the lead source, i am 100% sure this lead source does exist in our integration. please check this issue asap :).
array:44 [
  "Fax1Type" => "Other"
  "Company" => "Testing"
  "_OneTimeSetupFee" => 0
  "Email" => "test123@gmail.com"
  "AccountId" => 0
  "CompanyID" => 0
  "DateCreated" => array:3 [
    "date" => "2017-05-12 00:14:39.000000"
    "timezone_type" => 3
    "timezone" => "UTC"
  ]
  "PostalCode" => "20815"
  "Website" => "www.hellotesting.co.in"
  "ZipFour3" => "ABC"
  "LeadSourceId" => 30
  "JobTitle" => "Test"
  "ZipFour2" => "ABC"
  "Phone5Type" => "Work"
  "Leadsource" => "socialfuse.com"
]

**Comment by brumiser1550** [comment]
If Leadsource has already been set for a contact you cannot overwrite it with the API. Have you confirmed that no leadsource has been set. Try testing with a contact you create in the UI.

**Comment by coderanil** [comment]
yes leadSource is set by api 1st time after that its not updating, but i think leadSource is editable according to contact table schema(https://developer.infusionsoft.com/docs/table-schema/).

**Comment by brumiser1550** [comment]
You said "update contact api" so does that mean you are using updateCon method? What version of the sdk are you using? 

I have tested addWithDupCheck, updateCon, and dsUpdate and they all set Leadsource fine. 

Once a Leadsource is set it is not editable through the API.

**Comment by brumiser1550** [comment]
I just read your last comment again and you are correct. You can set it the first time and that is it.

**Comment by coderanil** [comment]
Yes i am using updateContact method, Can we do to it using this $infusionsoft->data()->update() ?
 or this is  a limitation of sdk or infusionsoft doesn't allow us to do so?.

**Comment by jwsmesaaz** [comment]
The reason why it shows as being editable is because the field can be changed from null to have a value. If a value other then null is in the field then the lead source won't update. The reason is that by definition that field is for the source of the Lead. A lead can only originally come from one source meaning that once a source is set that is where the Lead came from or the Lead's source.
