### ISSUE TITLE
How to insert special characters into infusionsoft

### ISSUE THREAD

**Issue by harshitnayak45** [infusionsoft/infusionsoft-php#124]
Can you let me know how can i insert special characters into Infusionsoft. Let say a name  "Yeuri Pérez " , i need to insert that name to a record. Please suggest

**Comment by bgpartridge** [comment]
May I direct you over to our [developer community](community.infusionsoft.com) That is the area where you can get input and suggestions from the community (including infusionsoft employees).  This repo is for handling bugs and issues with the SDK not "how to" questions.  Thanks!
