### ISSUE TITLE
An error occurred when fetching the URI 

### ISSUE THREAD

**Issue by archish1989** [infusionsoft/infusionsoft-php#125]
From sometime i am getting this error. Please can someone tell me why i am getting this error?
`exception 'Ivory\HttpAdapter\HttpAdapterException' with message 'An error occurred when fetching the URI "https://api.infusionsoft.com/crm/xmlrpc/v1?access_token=*******************" with the adapter "guzzle6" ("cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)").' in /home/*********/public_html/vendor/egeloen/http-adapter/src/HttpAdapterException.php:101`

my last stack trace says : 
Infusionsoft\Api\APIEmailService->optIn('cochinomail@*****...', 'chenge-status')
i am getting error here, and i don't get error on this function always. 

PS : Now every time i am getting this error.

**Comment by micfai** [comment]
Looks like this was a timeout error that was fixed with 1.3.2-beta.

@archish1989 are you still getting this error?

**Comment by sic-guno** [comment]
I'm seeing this on my IFS integration this morning, is anyone else?
