### ISSUE TITLE
404 for contactId on ContactService.load but not DataService.query

### ISSUE THREAD

**Issue by pfeiferchristopher** [infusionsoft/infusionsoft-php#126]
I'm having issues where the `contacts()->load($id, $fields)` is throwing 404 errors for a few of our customers in production but not everyone, and not our own internal app.

It is confirmed that the Contact IDs do exist, not only can we see them in their Infusionsoft accounts but when they search via `data()->query()` the Contact table they're found just fine by non-ID fields.

Any ideas are greatly appreciated.

**Comment by mfairch** [comment]
@pfeiferchristopher is this still happening?
