### ISSUE TITLE
How can i get Tag Category

### ISSUE THREAD

**Issue by algobasket** [infusionsoft/infusionsoft-php#127]
How can i get all Tag Category ?
Tag Category and display all tags in this category
Please help me

**Comment by coderanil** [comment]
You can get all tag categories using data query method like this
First find category id for your required category:
$categoryId = $this->infusionsoft->data->query('ContactGroupCategory',1, 0, ['CategoryName' => $yourCategoryName], ['Id'], ['Id'],true);
After this you will have to fetch all tags for this category:
$tags = $this->infusionsoft->data->query('ContactGroup',$limit, $page, $categoryId, ['GroupName'], ['Id'],true);

**Comment by algobasket** [comment]
Thanks :)

**Comment by iqbalmalik89** [comment]
Below one worked for me. 


```
$categoryId = $this->infusionsoft->data->query('ContactGroupCategory',1, 0, ['CategoryName' => $yourCategoryName], ['Id'], ['Id'],true);

$categoryId = array('GroupCategoryId' => $categoryId[0]['Id']);

$tags = $this->infusionsoft->data->query('ContactGroup',$limit, $page, $categoryId, ['GroupName'], ['Id'],true);
```
