### ISSUE TITLE
Return 123

### ISSUE THREAD

**Issue by limabibi** [infusionsoft/infusionsoft-php#128]
Hello,

I'm using the PHP API to add TAGS to the contacts already registered in the infusion, but when I use the command:

$ Infusionsoft-> contacts ('xml') -> addToGroup ($ contactId, $ tagId);

Without giving echo in this line, the page returns with the number 123, when I draw this line the page does not return anything, nor error.

I wonder what that 123 means?

Thanks.

**Comment by micfai** [comment]
You are getting `123`? It should be returning a true/false.
