### ISSUE TITLE
SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by ryrobbo** [infusionsoft/infusionsoft-php#129]
When attempting to refresh my Infusionsoft Token manually via requestAccessToken(), I get the following error:

GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: certificate has expired (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/thewebinarvet.com/laravel/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:187

This is only happening on a staging environment. On my local environment I am able to refresh the token no problem. Both environments are using separate REST secrets/accounts.

**Comment by micfai** [comment]
@ryrobbo did you ever figure this out? I'm assuming your local server's cert expired or the time on it is incorrect.

**Comment by ryrobbo** [comment]
After spending too much time attempting to update the server's CA store, I trashed the VPS and configured a fresh one. I've not experienced the error on the new server since.

**Comment by kimwue** [comment]
Having the same issue on my local development machine, Ubuntu 16. Any ideas? Trying to connect to the sandbox https://api-cert.payeezy.com/v1/transactions.

Same topic in payeezy forum:
https://developer.payeezy.com/content/sandbox-expired-ssl-certificate-api-certpayeezycom#comment-1531

Maybe related, news about certificate changes:
https://support.payeezy.com/hc/en-us/articles/223607367-Payeezy-Gateway-SSL-Certificate-Update-Details
https://developer.payeezy.com/content/certificate-update-httpsapipayeezycom-0726

**Comment by saifrehman15** [comment]
I have the same issues on windows 10 using docker. I got following error. 

cURL error 60: SSL certificate problem: certificate has expired (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
