### ISSUE TITLE
Google App Engine support

### ISSUE THREAD

**Issue by skeemer** [infusionsoft/infusionsoft-php#13]
I'm developing an app to run on Google App Engine and ran into a snag. It doesn't have the CURL extension. Guzzle doesn't need it in the newer versions. Can we get it upgraded?

**Comment by skeemer** [comment]
I haven't tested it yet, but I think we can close this as Google added the CURL extension. https://gae-php-tips.appspot.com/2014/11/15/app-engine-php-1-9-17-pre-release-sdk/

**Comment by andrewryno** [comment]
It's pre-release, but yeah considering I posted a basic workaround as well for older versions I'm going to go ahead and close it.
