### ISSUE TITLE
addManualPayment()Method always expects a 2-decimal float, even when impossible.

### ISSUE THREAD

**Issue by zackkrida** [infusionsoft/infusionsoft-php#131]
the [addManualPayment() method](https://github.com/infusionsoft/infusionsoft-php/blob/a2197e66f92db53a9238f9324f31b7d998c39450/src/Infusionsoft/Api/InvoiceService.php#L115) requires the `$amt` to be a `float`, quite specifically, a float with two **or more** decimal places:

```
Valid:
21.51
35.54
20.001
20.9999

Not Valid:
21.5
35
4203
2030.0
```

In ANY programming language I'm aware of, it is impossible to have a FLOAT with two empty decimal places (eg. `5.00 or 4.00`). They always get converted to have no decimal. I have **no clue how or why your api expects a float with mandatory 2 decimal places**. 

For reference, our solution for this is to *subtract every price by `-.001`*, so an invoice with a total of `15.00` will become `14.999` which gets rounded to `15` by the API. Crazy!

**Comment by mfairch** [comment]
@zackkrida I just did some testing using the "Not Valid" values you mentioned and the API and SDK accepted all of them without issue. Can you try again and let me know if an exception is thrown?

Test code I used in the addWithDupCheck.php sample file.

```php
    $contact = $infusionsoft->contacts()->with('custom_fields')->find($cid->id);

    $date = new \DateTime();

    $invoice = $infusionsoft->invoices()->createBlankOrder($contact->id, 'Test', $date, 0, 0);

    $item    = $infusionsoft->invoices()->addOrderItem($invoice, 20, 1, 21.5, 1, "Test", "Test");

    $payment = $infusionsoft->invoices()->addManualPayment($invoice, 21.5, $date, 'Manual', 'Test', false);

    var_dump($payment);
```
