### ISSUE TITLE
Strange error on local machine 

### ISSUE THREAD

**Issue by microdesign** [infusionsoft/infusionsoft-php#132]
HI without any updates of composer libs and not changing my code I start getting this error in my local ENV for $this->getObject()->contacts->findByEmail($user->email, ['ID'])

`HttpException in InfusionsoftSerializer.php line 34:
exception 'Ivory\HttpAdapter\HttpAdapterException' with message 'An error occurred when fetching the URI "https://api.infusionsoft.com/crm/xmlrpc/v1?access_token=TOKEN" with the adapter "guzzle6" ("cURL error 6: name lookup timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)").' in /Volumes/Storage/Projects/argoApp/argoapp/vendor/egeloen/http-adapter/src/HttpAdapterException.php:101
Stack trace:
#0 /Volumes/Storage/Projects/argoApp/argoapp/vendor/egeloen/http-adapter/src/Guzzle6HttpAdapter.php(68): Ivory\HttpAdapter\HttpAdapterException::cannotFetchUri(Object(Zend\Diactoros\Uri), 'guzzle6', 'cURL error 6: n...')
#1 /Volumes/Storage/Projects/argoApp/argoapp/vendor/egeloen/http-adapter/src/HttpAdapterTrait.php(110): Ivory\HttpAdapter\Guzzle6HttpAdapter->sendInternalRequest(Object(Ivory\HttpAdapter\Message\InternalRequest))
#2 /Volumes/Storage/Projects/argoApp/argoapp/vendor/egeloen/http-adapter/src/HttpAdapterTrait.php(101): Ivory\HttpAdapter\AbstractHttpAdapter->sendRequest(Object(Ivory\HttpAdapter\Message\InternalRequest))
#3 /Volumes/Storage/Projects/argoApp/argoapp/vendor/egeloen/http-adapter/src/HttpAdapterTrait.php(54): Ivory\HttpAdapter\AbstractHttpAdapter->send('https://api.inf...', 'POST', Array, '<?xml version="...', Array)
#4 `

System is on Laravel 

"laravel/framework": "5.2.*",
"infusionsoft/php-sdk": "^1.2",

**Comment by micfai** [comment]
Sounds like you have a DNS issue locally with curl.

**Comment by microdesign** [comment]
What is my options - maybe the only think I update before it stop working is my macOS to the latest version from ElCapitan - can this be related - but I think it must come from the MAMP installation which is same as before it stop working.

**Comment by microdesign** [comment]
Great support - closing tickets without answers of questions

**Comment by toddstoker** [comment]
I'm not familiar with MAMP, so I can't offer much help there outside of Google.

It looks like you're using Laravel, I recommend checking out Valet or Vagrant for your local dev environment. Best of luck to you!
