### ISSUE TITLE
FunnelService::achieveGoal not working?

### ISSUE THREAD

**Issue by laurent22** [infusionsoft/infusionsoft-php#133]
I've got a goal setup on the CRM and got the Integration and Call Name from it. Then, using the PHP SDK, I've created a contact (this worked fine) and then tried to achieve the goal using this code:

    $client->funnels()->achieveGoal($goalIntegration, $callName, $contactId);

But that doesn't work as I simply get this error:

````
array(1) {
  [0]=>
  array(6) {
    ["success"]=>
    bool(false)
    ["msg"]=>
    string(54) "No Goals were configured to be achieved by this event."
    ["funnelId"]=>
    int(0)
    ["goalId"]=>
    int(0)
    ["flowStart"]=>
    array(0) {
    }
    ["flowStop"]=>
    array(0) {
    }
  }
}
````

I've checked all the input variables and they all have the right values and they match what's in the CRM.

Any idea what is causing this and how to get it to work?

**Comment by micfai** [comment]
@laurent22 this could be caused if the campaign isn't published. I would check that next time this happens.
