### ISSUE TITLE
Warning: Ambiguous class resolution

### ISSUE THREAD

**Issue by andreladocruz** [infusionsoft/infusionsoft-php#134]
When updating composer I got the following warning:

Warning: Ambiguous class resolution, "Infusionsoft\Api\AbstractApi" was found in both "./vendor/infusionsoft/php-sdk/src/Infusionsoft/Api/AbstractApi.php" and "./vendor/infusionsoft/php-sdk/src/Infusionsoft/Api/Rest/RestApi.php", the first will be used.

Is there a way to avoid it?

And there is the egeloen/http-adapter that is abandoned too.

**Comment by grupoapok** [comment]
Both files have a different name, but the same signature on the class definition.
