### ISSUE TITLE
Invalid Refresh Token

### ISSUE THREAD

**Issue by khyler** [infusionsoft/infusionsoft-php#137]
I'm trying to record emails to client infusionsoft accounts using the Log Sent Email method.

However, when I try to actually use the method I'm getting the following fatal error:
```
Fatal error:  Uncaught exception 'Infusionsoft\Http\HttpException' with message 'exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://api.infusionsoft.com/token` resulted in a `400 Bad Request` response:
{"error":"invalid_grant","error_description":"Invalid refresh token"}
```
My logic behind this, is that each user that needs to log a sent email to a clients file, must click the link to authorize themselves, which assigns the token for their current session. 

```
$infusionsoft = new \Infusionsoft\Infusionsoft(array(
    'clientId' => '************************',
    'clientSecret' => '**********',
    'redirectUri' => 'https://mydomain.com/scp/tickets.php?status=open',
));

if (isset($_SESSION['token'])) {
    $infusionsoft->setToken(unserialize($_SESSION['token']));
}
if (isset($_GET['code']) and !$infusionsoft->getToken()) {
    $_SESSION['token'] = serialize($infusionsoft->requestAccessToken($_GET['code']));
}
if ($infusionsoft->getToken()) {
    $_SESSION['token'] = serialize($infusionsoft->getToken());
} else {
	echo '<a href="' . $infusionsoft->getAuthorizationUrl() . '" style="color:#ff0000;">Click here to authorize</a>'; 
}
```

Once they're authorized, they can then proceed to recording the email using a simple form with the clients information.

```
if ( isset($_POST["email"]) ) {
	
	$infusionsoft->refreshAccessToken();

	$contactId = 123;
	$fromName = "John Doe";
	$fromAddress = "JDoe@test.com";
	$toAddress = "Tester@test.com";
	$ccAddresses = "cc@test.com";
	$bccAddresses = "testerson@test.com";
	$contentType = "TEXT";
	$subject = "test subject";
	$htmlBody = "html here";
	$textBody = "Test Body Can Be Anything";
	$header = "Email header";
	$receivedDate = date('Ymj\TG:i:s');
	$sentDate = date('Ymj\TG:i:s');
	$emailSentType = 1;
	$infusionsoft->emails()->attachEmail($contactId, $fromName, $fromAddress, $toAddress, $ccAddresses, $bccAddresses, $contentType, $subject, $htmlBody, $textBody, $header, $receivedDate, $sentDate, $emailSentType);
}
```

Is this because, each user is authorizing themselves  to get a token, subsequently not allowing the refeshAccessTokens to match?

**Comment by micfai** [comment]
@khyler  Did you ever figure this out? I'm assuming it's due to some weird session state causing the refresh token to not update or be null.

**Comment by khyler** [comment]
@micfai  I'm not entirely sure to be honest. I'm trying to implement this into OSTicket which does has some rather odd usage of  sessions.

**Comment by mfairch** [comment]
@khyler I was looking more into OSTicket session handling and it doesn't look like they do anything crazy with the sessions, they just get cleared frequently. Did you ever figure out a workaround?
