### ISSUE TITLE
URGENT: "Failed to invoke method chargeInvoice" Same response for successful and declined charges.

### ISSUE THREAD

**Issue by cliftonscott** [infusionsoft/infusionsoft-php#138]
I'm using the 1.2. package and have started getting this error when trying to charge an invoice.
`Failed to invoke method chargeInvoice`

Nothing has been changed and the error just started occurring.

Any ideas on a cause? Thanks!

**Comment by cliftonscott** [comment]
The response I receive when making the chargeInvoice call is "Failed to invoke method chargeInvoice in class com.infusionsoft.api.xmlrpc.XmlRpcInvoiceService: null"

**Comment by cliftonscott** [comment]
All responses from the chargeInvoice method is "Failed to invoke method chargeInvoice" but the invoice is still being charged. It's the same reason for successful charges and declined charges.

**Comment by cliftonscott** [comment]
@micfai Any updates on this? Thanks!

**Comment by KelseySheely** [comment]
I am also getting this error for one of my clients.  I have an open ticket and still waiting on a resolution.  Infusionsoft support was able to duplicate the error and they are currently investigating.

**Comment by micfai** [comment]
This is not an issue with the SDK, it's an issue with the api. Please submit a ticket about it.
https://developer.infusionsoft.com/support/tickets/create/

**Comment by cliftonscott** [comment]
@micfai Thanks. Tickets have been submitted without resolution. I believe this is urgent as if we can't tell if an invoice is charged successfully or not. Little movement via tickets, thus turning to Github.

**Comment by micfai** [comment]
@cliftonscott We have developers actively looking at the issue so be on the lookout for a resolution soon.

**Comment by elnicoar** [comment]
Adding the following fields to the CreditCard array: ‘BillAddress1’, ‘BillCity’, ‘BillState’, ‘BillZip’, ‘Email’

So our code is now as follows:

```
//add credit card
$newCard = array(
  'ContactId' => $cid,
  'NameOnCard' => $_POST['ccName'],
  'CardNumber' => $_POST['ccNum'],
  'CardType' => $_POST['ccType'],
  'CVV2' => $_POST['ccCode'],
  'ExpirationMonth' => $_POST['ccMonth'],
  'ExpirationYear' => $_POST['ccYear'],
  'BillAddress1' => $_POST['Street'],
  'BillCity' => $_POST['City'],
  'BillState' => $_POST['State'],
  'BillZip' => $_POST['Zip'],
  'Email' => $_POST['email'],
);

$newCardId = $app->dsAdd('CreditCard',$newCard);
```
