### ISSUE TITLE
Infusionsoft exception

### ISSUE THREAD

**Issue by Gardezi1** [infusionsoft/infusionsoft-php#139]
Hello, guys, I need to log the exception that I get when trying to save data on infusion soft via API. The problem is you guys are returning me a string which has stacktrace with it which is of no use to me. I just need to get the error message. Can you guys please help me out 

and one more thing the error code that you are sending is 0 but in the message, it is 400. Can you guys please tell me how to resolve it thanks 

Below I've attached a image. Please help me out thanks 
[image removed due to access token shown]

**Comment by micfai** [comment]
Your request isn't formatted correctly. See my comment on https://github.com/infusionsoft/infusionsoft-php/issues/136#issuecomment-322783196

**Comment by Gardezi1** [comment]
@micfai thanks but I'm not having a problem with the formating. I know it's wrong. I formatted it incorrectly so that I can get an error. The problem that I'm having is with the exception being thrown when I try to save something in infusionsoft. 

The thing is I need to keep a record of what went wrong and what error code was returned. Currently the exception that is returned from infusion has everything populated in the message (the error code, message and the stacktrace). 

[CODE]
\Log::debug("The error code is : ". $e->getCode());
\Log::debug("The error message is : ". \GuzzleHttp\json_decode($e->getMessage()));

[/CODE]

 where $e is the exception object and values returned by the aboove log are shown below in the picture

![asdasd](https://user-images.githubusercontent.com/13199724/29397494-01d06d1c-8338-11e7-95e1-406494126321.png)

The error code that is being returned when I try `$e->getCode()` is 0 which is wrong because from the I can clearly see that we are getting 400. 

And stacktrace is coming with the message which I do not need. I just need the message and that's it. Can you guys please help me out Thanks

**Comment by Gardezi1** [comment]
I dumped the message and this is what I'm getting. I just need the message of what went wrong not the stacktrace with it 

![vardumpimage](https://user-images.githubusercontent.com/13199724/29397925-dfdb3a90-833a-11e7-9450-a6eeffa3ebad.png)

**Comment by Fly1nP4nda** [comment]
Hey @Gardezi1 see #150 - that might be what you are looking for.
