### ISSUE TITLE
Authenticated User Info

### ISSUE THREAD

**Issue by merlindiavova** [infusionsoft/infusionsoft-php#14]
I'm adding Infusionsoft to a social login plugin of mine and i want to retrieve their basic information such as first name, last name and user id. Now when a user has completed the OAuth flow i do not see a way to retrieve the this info. Any advise?

**Comment by micfai** [comment]
Take a look at DataService.getUserInfo

https://github.com/infusionsoft/infusionsoft-php/blob/master/src/Infusionsoft/Api/DataService.php#L152

This method requires OAuth2 and an active access token and can not be used with our legacy API Key.

**Comment by merlindiavova** [comment]
Thanks
