### ISSUE TITLE
Not getting custom key when retrieving  contact list using restapi

### ISSUE THREAD

**Issue by Gardezi1** [infusionsoft/infusionsoft-php#141]
Hello, guys, I have made some custom keys using your web view. Now I’m saving the data in which I have placed the custom keys with an underscore at the start but the problem is when I try to retrieve the data I don’t get the custom key. Can somebody tell me what is going wrong?

I’m using rest API
```
infusionsoftService->contacts()->get()
```

The get function is not present in your contactService but it is present in the restmodel

**Comment by micfai** [comment]
Are you referring to custom fields? In Rest you will only get the field content when querying a single contact. Custom Fields also return using their Id instead of the name in Rest.

**Comment by Gardezi1** [comment]
so if I need custom key of a contact or anything I need to single call to get the data. 

When I retrieve the list I won't be getting the custom keys. Am I correct ??

**Comment by mfairch** [comment]
@Gardezi1 we recently changed the contact list endpoint to return custom fields if you request them using `->with('custom_fields')`. This should solve your issue correct?
