### ISSUE TITLE
Call to undefined method Infusionsoft\Api\Rest\ContactService::addToGroup()

### ISSUE THREAD

**Issue by rafaelwedbiz** [infusionsoft/infusionsoft-php#142]
How to apply tags in a contact?

**Comment by micfai** [comment]
You are using rest so it's a little bit different.

```
$contact->addTags([123,456,789]);
```

**Comment by rafaelwedbiz** [comment]
Thanks, it worked !
I installed it with composer 1.3 version, how to not use rest?

**Comment by micfai** [comment]
https://github.com/infusionsoft/infusionsoft-php#breaking-change

**Comment by rafaelwedbiz** [comment]
Thanks.
if i put $infusionsoft->contacts('xml')->addToGroup(32883, 652); , it will work?

**Comment by micfai** [comment]
It is better top use rest when applying tags. addToGroup can only do 1 tag per api call where rest can do up to 100 tags per api call.

**Comment by rafaelwedbiz** [comment]
understand, thanks so much :)
