### ISSUE TITLE
Frequent Error "Operation timed out after 10000 milliseconds" when try to use getSavedSearchResultsAllFields

### ISSUE THREAD

**Issue by rafaelwedbiz** [infusionsoft/infusionsoft-php#143]
I have a script that run getSavedSearchResultsAllFields, sometime it works but i'm getting serveral timeout error:

**Fatal error: Uncaught exception 'Infusionsoft\Http\HttpException' with message 'exception 'Ivory\HttpAdapter\HttpAdapterException' with message 'An error occurred when fetching the URI "https://api.infusionsoft.com/crm/xmlrpc/v1?access_token=***********" with the adapter "guzzle6" ("cURL error 28: Operation timed out after 10000 milliseconds with 39370 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)").' in *****************/vendor/egeloen/http-adapter/src/HttpAdapterException.php:101 Stack trace: #0 *****************/vendor/egeloen/http-adapter/src/Guzzle6HttpAdapter.php(68): Ivory\HttpAdapter\HttpAdapterException::cannotFetchUri(Object(Zend\Diactoros\Uri), 'guzzle6', 'cURL error 28: ...') #1 *****************/vendor/egeloen/http-adapter/src/HttpAdapterTrait.php(110): Ivory\HttpAdapter\Guzzle6HttpAdapter->sendInternalRequest(Object(Ivory\HttpAdapter\Message\InternalRequest)) #2 *****************/vendor/egeloen/http-adapter/src/HttpAdapterTrait.php(101): Ivory\HttpAdapter\AbstractHttpAda in *****************/vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/InfusionsoftSerializer.php on line 34**

**Comment by micfai** [comment]
@rafaelwedbiz what version of the SDK are you using? In 1.3.2-beta the timeout for Guzzle was increased to 60 seconds.
