### ISSUE TITLE
Set Contact id in REST API

### ISSUE THREAD

**Issue by denisloshkarev** [infusionsoft/infusionsoft-php#149]
https://github.com/infusionsoft/infusionsoft-php/blob/56d0bc3bd03fc2ea358dc983dbe532bb2ebe7934/src/Infusionsoft/Api/Rest/ContactService.php#L42

Hi guys. I didn't find any method to set contact id that use in this class.
I found that in each class used $this->id variable but this is the magic field and it isn't documented.
Just want to know, is there present any method to set the contact id to use it in REST API?
Or I'm welcome to make pull request to fix it?

**Comment by micfai** [comment]
Currently you have to do a `find($id)` to set it however we might be able to add a way for you to set it without having to do a find.

I will look more into this.

**Comment by denisloshkarev** [comment]
But, as I understood, `find($id)` will send another one request, right?

**Comment by micfai** [comment]
Yes which is why I am going to look into being able to set that id instead of having to make another request.

**Comment by denisloshkarev** [comment]
Okay, thanks.

**Comment by micfai** [comment]
@denisloshkarev I forgot that this actually does already exist, you use the mock method and set the id.

```
$infusionsoft->contacts()->mock(['id' => 123])->addTags([123])
```

**Comment by denisloshkarev** [comment]
@micfai Thank you. It will be useful.
Not sure that my new question should be in new issue, so...
I not found class to work with Tags via REST API, I already created it by myself, but just want to know, do you work with it now? Do you plan to implement it?

**Comment by micfai** [comment]
@denisloshkarev are you referring to the TagService? https://github.com/infusionsoft/infusionsoft-php/blob/master/src/Infusionsoft/Api/Rest/TagService.php

**Comment by denisloshkarev** [comment]
@micfai Yes, I just found it. Don't know why it isn't present in my project, I'll check the library's version.

**Comment by micfai** [comment]
@denisloshkarev I'm closing this issue as it appears everything is working for you related to this issue.
