### ISSUE TITLE
Error using PHP API.. 

### ISSUE THREAD

**Issue by dave-in-fuzed** [infusionsoft/infusionsoft-php#15]
Hi,

I'm wondering where is the file 'vendor/autoload.php;' on the SDK. I've tried downloading the .zip file but it was not included. 

Alternatively, I did include the files like this on my CodeIgniter Views (I'm sure what I'm doing):

require_once APPPATH.'libraries/infusionsoft2/src/Infusionsoft/Infusionsoft.php';
require_once APPPATH.'libraries/infusionsoft2/src/Infusionsoft/InfusionsoftException.php';
require_once APPPATH.'libraries/infusionsoft2/src/Infusionsoft/Token.php';
require_once APPPATH.'libraries/infusionsoft2/src/Infusionsoft/TokenExpiredException.php';
require_once APPPATH.'libraries/infusionsoft2/src/Infusionsoft/Http/CurlClient.php';
require_once APPPATH.'libraries/infusionsoft2/src/Infusionsoft/Http/ClientInterface.php';
require_once APPPATH.'libraries/infusionsoft2/src/Infusionsoft/Http/GuzzleClient.php';						
require_once APPPATH.'libraries/infusionsoft2/src/Infusionsoft/Http/HttpException.php';
require_once APPPATH.'libraries/infusionsoft2/src/Infusionsoft/Http/SerializerInterface.php';
require_once APPPATH.'libraries/infusionsoft2/src/Infusionsoft/Http/InfusionsoftSerializer.php';

but its says 

Fatal error: Class 'fXmlRpc\Transport\CurlTransport' not found in /srv/users/serverpilot/apps/test/public/application/libraries/infusionsoft2/src/Infusionsoft/Http/CurlClient.php on line 7

I also tried finding the class CurlTransport, but I think it is not existing..

Any help,

Thanks,

**Comment by micfai** [comment]
You need to run "composer install" to download all of the dependencies.

**Comment by dave-in-fuzed** [comment]
Can you provide a downloadable files including all the dependency in one zip file?

Its really painful working with composer on my part right now. fI you have in your computer just zip and send a link to me..

Thank you so much..
