### ISSUE TITLE
Example doc fails with "undefined method named 'add' of class Infusionsoft\Api\Rest\ContactService"

### ISSUE THREAD

**Issue by jakenoble** [infusionsoft/infusionsoft-php#151]
I am using the docs on https://github.com/infusionsoft/infusionsoft-php I am getting this errors

> Attempted to call an undefined method named "add" of class "Infusionsoft\Api\Rest\ContactService".
> Did you mean to call e.g. "addHidden", "addTags" or "addVisible"?

When using 

```
$infusionsoft->contacts->add(array('FirstName' => 'John', 'LastName' => 'Doe'));
```

Same error with this too

```
$c = $infusionsoft->contacts();
$c->add(array('FirstName' => 'John', 'LastName' => 'Doe'));
```

**Comment by micfai** [comment]
I updated the example in the readme. You need to do `$infusionsoft->contact('xml')->add()`. v1.3 defaulted the contacts to using the rest api. If you'd prefer to use the rest api, check out the addWithDupCheck.php in the sample folder.
