### ISSUE TITLE
REST API update contact error

### ISSUE THREAD

**Issue by dkaitou** [infusionsoft/infusionsoft-php#154]
Hi Guys,

Have you seen this error while you are updating an empty custom_fields on contact ? 
"Tags can't be added or removed through this object"

Here is the code that generated the error:  
`$contact = $objInfusionsoft->contacts()->find(71);`
`$contact->custom_fields = [['content' => date('Y-d-m') , 'id' =>17]]  ;`
`$contact->save();`

Is there anything wrong that I have used ?
Do I have to use "addCustomField()" from DataService class ?  If yes, is there any documentation to show how to do that ? 

Thank you.

**Comment by dkaitou** [comment]
For anyone who is getting the error "Tag can't be added or removed through this object" while updating custom_fields by REST API.

This code can overcome the issue(I have tested it and it's working ):
`$contact = $objInfusionsoft->contacts()->find(71);`
`unset($contact['tag_ids']);`
`$contact->custom_fields = [['content' => date('Y-d-m') , 'id' =>17]] ;`
`$contact->save();`

**Comment by hi2u** [comment]
Hi @dkaitou ...

Do you happen to have any idea where I find these ID numbers for custom fields in Infusionsoft's control panel?

I'm working on a system that was built by someone else.  And the code using the API has these custom field ID numbers everywhere.  Yet I can't find where they are actually set up in Infusionsoft's control panel.

**Comment by larsenkevin** [comment]
If you hover over the edit link in step 8 look at the url and you will see
the id.

https://help.infusionsoft.com/userguides/get-started/create-custom-fields/create-custom-fields
