### ISSUE TITLE
sending binary data in data add api

### ISSUE THREAD

**Issue by akprgm** [infusionsoft/infusionsoft-php#155]
I am trying to add a new product in infusionsoft product table by data api. Product table schema says LargeImage field should be of type of Blob(https://developer.infusionsoft.com/docs/table-schema/).
I have array with with binary data eg $arr =["ProductName" => "jeans", "LargeImage"=>"some binary data"];

When i call $infusionsoft->data->add('Product', $arr) this api, it show error "Invalid byte 1 of utf8-sequence", api works fine with other params and i am to create a product.

Also when i try to access existing product via data query api, i do not get 'LargeImage' field of product.

 eg.   This product have an image.

Log::info($this->infusionsoft->data->query('Product',1,0,['Id'=>'~>=~0'],['Id','ProductName','LargeImage'],'Id', false));

[2017-10-31 03:28:23] local.INFO: array (
  0 => 
  array (
    'ProductName' => 'new fixed plan',
    'LargeImage' => '',
    'Id' => 8,
  ),
) 
 
need help!

**Comment by mfairch** [comment]
@akprgm base64 encode the image. As a note, the `LargeImage` column is only used for legacy shopping cart images, there currently isn't an endpoint to add images to Products in the api.
