### ISSUE TITLE
Unauthorized, Not Invalid Token

### ISSUE THREAD

**Issue by pfeiferchristopher** [infusionsoft/infusionsoft-php#158]
Hello,

I'm using this SDK to allow functions from my app from Infusionsoft. And I'm getting the response "Unauthorized" with no further information from some of my customer's accounts when they are trying to load their own Contact's details.

I'm using the `Infusionsoft::contacts()->load($contactId, $fields);` method; I also know for a fact the token is not invalid and has not expired because before and after this error response I was able to retrieve the Fields via Data service with the same access token.

Are there different sections of the API that might have different permissions? If so, how can I code to be prepared for this.

**Comment by mfairch** [comment]
@pfeiferchristopher did you ever get this worked out?

**Comment by jhourlad** [comment]
Seems nobody's really checking these issues. I'm deeply hurt.
