### ISSUE TITLE
Check for Duplicate Contact in IS

### ISSUE THREAD

**Issue by BharviManvar** [infusionsoft/infusionsoft-php#159]
Hello Team,

I am using third party SDK for infusionsoft API. and when i create contact in infusionsoft that time check the condition same contact exists or not so which function will use?

Please give me suggestion.

Thanks & Regards,
Bharvi Manvar

**Comment by mfairch** [comment]
These issues are specifically for issues with the SDK and not general API questions. Please use our [community](https://community.infusionsoft.com/c/api) for that
