### ISSUE TITLE
Please, support an OOB OAuth flow

### ISSUE THREAD

**Issue by igorsantos07** [infusionsoft/infusionsoft-php#161]
I'm basically reopening https://github.com/infusionsoft/infusionsoft-php/issues/97 so the problem stays open until a better solution is found.

Currently, to feed CLI scripts we have to spin up a web server just to get the user's OAuth token. That means we have to run a server just for setup. And that might be needed from time to time since tokens may be deauthorized.

A _very_ simple, accepted standard and clever way to solve that is with a copy-paste page, also called [_out-of-band flow_](https://stackoverflow.com/questions/13522497/what-is-oob-in-oauth): we ran a command that opens the user browser directly on the IFS Auth URL, with a specific `redirectUri` (usually `urn:ietf:wg:oauth:2.0:oob`) that would then prompt the user to copy the presented token into the CLI script.

![Google's copy-paste page](https://developers.google.com/accounts/images/installedresult.png)

That is currently supported by other automation-ready APIs, such as [Google](https://developers.google.com/identity/protocols/OAuth2InstalledApp#request-parameter-redirect_uri) (actually, who created this method), [Twitter](https://developer.twitter.com/en/docs/basics/authentication/overview/pin-based-oauth), [Asana](https://asana.com/developers/documentation/getting-started/auth#register-an-app), and so on.

Hope this gets into the pipeline soon, as the issue was ignored a year ago, but it's still a pain for the SDK users - in probably any language around. And it doesn't seem any API user is happy with the suggestions to use a fourth-party(?) tool such as Runscope to solve a matter that IFS API should be solving by itself.

**Comment by mfairch** [comment]
@igorsantos07 We don't support the OOB flow 100% yet however you can achieve a similar result that we added in our Aug release.

https://help.infusionsoft.com/release-notes/august-update-2017#simplified

**Comment by igorsantos07** [comment]
Hmmm is this documented anywhere besides a blog post, @mfairch? This should be clear on the SDK docs, as well as any other doc mentioning usage of OAuth.
