### ISSUE TITLE
Update contact's Custom Field Value.

### ISSUE THREAD

**Issue by raphcadiz** [infusionsoft/infusionsoft-php#163]
I've been going to the docs https://developer.infusionsoft.com/docs/xml-rpc/#contact-update-a-contact but I'm not able to update a contact's custom field value.  I can't find a way to update it. I tried something like this:

```
$mapping['custom_fields'] = array(
        'content' => 'Test Content',
         'id'    => 1 );

$infusionsoft->contacts('xml')->update($contact_details[0]['Id'], $mapping);
```

but I'm getting an error field not found.
Anyone tried updating a contact's custom field value before using this php library?

**Comment by brumiser1550** [comment]
It needs to be an array of arrays.

$mapping['custom_fields'] = [
    ['id' => 1,
     'content' => 'Test Content'
    ],
]

**Comment by raphcadiz** [comment]
@brumiser1550 thanks for the reply, I tried that way also
```
$mapping['custom_fields'] = [
                    [
                        'content' => 'Test Degree',
                        'id'    => 1
                    ]
                ];
```

unfortunately I'm still getting the error field not found. It seem it just check for the columns of the Contact table and not for custom fields.


`Fatal error: Uncaught fXmlRpc\Exception\FaultException: [NoFieldFound]No field found: Contact.custom_fields in /home/vagrant/Code/wordpress/wp-content/plugins/gravity2infusionsoft/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Exception/FaultException.php:32 Stack trace: #0 /home/vagrant/Code/wordpress/wp-content/plugins/gravity2infusionsoft/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Parser/XmlReaderParser.php(373): fXmlRpc\Exception\FaultException::fault(Array) #1 /home/vagrant/Code/wordpress/wp-content/plugins/gravity2infusionsoft/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Client.php(153): fXmlRpc\Parser\XmlReaderParser->parse('<?xml version="...') #2 /home/vagrant/Code/wordpress/wp-content/plugins/gravity2infusionsoft/vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/InfusionsoftSerializer.php(28): fXmlRpc\Client->call('ContactService....', Array) #3 /home/vagrant/Code/wordpress/wp-content/plugins/gravity2infusionsoft/vendor/infusionsoft/php-sdk/src/Infusionsoft/Infusionsoft.php(431): Infusionsoft\Http\InfusionsoftSerializer->request('ContactS in /home/vagrant/Code/wordpress/wp-content/plugins/gravity2infusionsoft/vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/InfusionsoftSerializer.php on line 34`

**Comment by brumiser1550** [comment]
Hey there, 

Sorry, I read this too fast the first time. 

You only use the Id/Content method when using the REST API. You can do something like so. 

`
$save = $infusionsoft->contacts()->create([
                'id' => 63,
                'custom_fields' => [
                    ['id' => 1,
                        "content" => 123456
                    ]
                ]
            ]);
`
Although it says create, by setting the id, it will cause it to run a PATCH request when the Save() method is called internally. 

If you want to update using the XML way you need to pass the field names like so 

`
$save = $infusionsoft->contacts('xml')->update(63, [
                '_clickCount' => 123456,
            ]);
`

Hope this helps

**Comment by raphcadiz** [comment]
@brumiser1550 it didn't really work. Here is the content of the array I passed

```
Array
(
    [LastName] => kopl
    [custom_fields] => Array
        (
            [0] => Array
                (
                    [content] => Test Degree
                    [id] => 1
                )
        )
)
```

with this code
`$infusionsoft->contacts()->create($mapping, true);`

and this for xml

`$infusionsoft->contacts('xml')->update($contact_id, $mapping);`

**Comment by brumiser1550** [comment]
I'm on mobile now so sorry for formatting.

See my last post. If you use xml you have to pass the data as fieldname =>
value, not using the ID and content.

$mapping = ['LastName' => 'kolob', '_yourcustomfield' =>'some value' ];
$update = $infusionsoft->contacts('xml')->update($contact_id, $mapping);

Your data is not correct for doing an update using rest. I do not believe
there is a second parameter in the create method. Also, you should pass an
id => $contact_id in your mapping.

(i copy/pasted, use correct php here obviously)
$mapping = Array

(

    [id]  => $contactid
    [LastName] => kopl
    [custom_fields] => Array
        (
            [0] => Array
                (
                    [content] => Test Degree
                    [id] => 1
                )
        )
)


$create = $infusionsoft->contacts()->create($mapping);


On Jan 3, 2018 22:35, "Raph Cadiz" <notifications@github.com> wrote:

@brumiser1550 <https://github.com/brumiser1550> it didn't really work. Here
is the content of the array I passed

Array
(
    [LastName] => kopl
    [custom_fields] => Array
        (
            [0] => Array
                (
                    [content] => Test Degree
                    [id] => 1
                )
        )
)

with this code
$infusionsoft->contacts()->create($mapping, true);

and this for xml

$infusionsoft->contacts('xml')->update($contact_id, $mapping);

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/infusionsoft/infusionsoft-php/issues/163#issuecomment-355197115>,
or mute the thread

**Comment by raphcadiz** [comment]
> Your data is not correct for doing an update using rest. I do not believe
> there is a second parameter in the create method. Also, you should pass an
> id => $contact_id in your mapping.

There is a second parameter `$dupCheck` if TRUE metho `put` is used

> See my last post. If you use xml you have to pass the data as fieldname =>
> value, not using the ID and content.

This is exactly the 1st problem I'm talking about, when we use the fieldname on the custom field, I get the error `No field found`

**Comment by brumiser1550** [comment]
Does the custom field exist?

Can you post your code, data, and the error messages?

**Comment by brumiser1550** [comment]
For $create = $infusionsoft->contacts()->create($mapping);

If you visit https://github.com/infusionsoft/infusionsoft-php/blob/master/src/Infusionsoft/Api/Rest/RestModel.php you will see that the create method in fact does not take a second parameter.

**Comment by raphcadiz** [comment]
hmmn, not sure about that. When we use xml it will use the class
https://github.com/infusionsoft/infusionsoft-php/blob/master/src/Infusionsoft/Api/ContactService.php

not https://github.com/infusionsoft/infusionsoft-php/blob/master/src/Infusionsoft/Api/Rest/RestModel.php

see
https://github.com/infusionsoft/infusionsoft-php/blob/master/src/Infusionsoft/Infusionsoft.php#L577

**Comment by brumiser1550** [comment]
This  $create = $infusionsoft->contacts()->create($mapping);
Is not xml service, it's rest. 

This
$mapping = ['LastName' => 'kolob', '_yourcustomfield' =>'some value' ];
$update = $infusionsoft->contacts('xml')->update($contact_id, $mapping);
Is xml service

**Comment by raphcadiz** [comment]
Yes, and $infusionsoft->contacts() goes to
https://github.com/infusionsoft/infusionsoft-php/blob/master/src/Infusionsoft/Api/Rest/ContactService.php
in which create has 2nd parameter

**Comment by raphcadiz** [comment]
From here
https://github.com/infusionsoft/infusionsoft-php/blob/master/src/Infusionsoft/Infusionsoft.php#L583
It calls the function getRestApi which is this 
https://github.com/infusionsoft/infusionsoft-php/blob/master/src/Infusionsoft/Infusionsoft.php#L803

and then will call Infusionsoft\Api\Rest\ContactService

**Comment by brumiser1550** [comment]
You're correct, I missed that ContactService overrode the create method; I'm on mobile do it is more cumbersome.

Regardless that should still work. Can you post the error and the call it comes from.

**Comment by raphcadiz** [comment]
The error I posted above
`Fatal error: Uncaught fXmlRpc\Exception\FaultException: [NoFieldFound]No field found: Contact.custom_fields in /home/vagrant/Code/wordpress/wp-content/plugins/gravity2infusionsoft/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Exception/FaultException.php:32 Stack trace: #0 /home/vagrant/Code/wordpress/wp-content/plugins/gravity2infusionsoft/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Parser/XmlReaderParser.php(373): fXmlRpc\Exception\FaultException::fault(Array) #1 /home/vagrant/Code/wordpress/wp-content/plugins/gravity2infusionsoft/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Client.php(153): fXmlRpc\Parser\XmlReaderParser->parse('<?xml version="...') #2 /home/vagrant/Code/wordpress/wp-content/plugins/gravity2infusionsoft/vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/InfusionsoftSerializer.php(28): fXmlRpc\Client->call('ContactService....', Array) #3 /home/vagrant/Code/wordpress/wp-content/plugins/gravity2infusionsoft/vendor/infusionsoft/php-sdk/src/Infusionsoft/Infusionsoft.php(431): Infusionsoft\Http\InfusionsoftSerializer->request('ContactS in /home/vagrant/Code/wordpress/wp-content/plugins/gravity2infusionsoft/vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/InfusionsoftSerializer.php on line 34`

**Comment by brumiser1550** [comment]
And that is using the xml service? Did you pass your data like this 

$mapping1 = ['LastName' => 'kolob', '_yourcustomfield' =>'some value' ];
or like this 
$mapping2 = [
                   'id' => $contact_id
                   'custom_fields' => [
                        'content' => 'Test Degree',
                        'id'    => 1
                    ]
                ];

$mapping1 goes to 
$update = $infusionsoft->contacts('xml')->update($contact_id, $mapping);

$mapping2 goes to 
$update2 = $infusionsoft->contacts()->create($mapping2);

**Comment by raphcadiz** [comment]
It’s good now. Thanks for your help
