### ISSUE TITLE
MySQL error (!!!) on empty IN queries

### ISSUE THREAD

**Issue by igorsantos07** [infusionsoft/infusionsoft-php#164]
Running something like `$client->data()->query('Contact', 1000, 0, ['Id' => []], ['Id'], 'Id', false)` yields a MySQL(!!!!) error stating a bad query:

> Uncaught fXmlRpc\Exception\FaultException: Failed to invoke method query in class com.infusionsoft.api.xmlrpc.XmlRpcDataService: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ORDER BY Contact.Id DESC LIMIT 0,1000'

It's funny because the SDK complains about the IDs not being `int`s (while single ID queries work transparently), but not even verifying if the array is empty. Not even the API server verifies that (!!)

**Comment by mfairch** [comment]
Thanks for the heads up. We'll take a look.

**Comment by igorsantos07** [comment]
Glad to know that at least security issues are quickly looked after - because some other issues here......
