### ISSUE TITLE
Contacts XML addToGroup() return error

### ISSUE THREAD

**Issue by Xavious** [infusionsoft/infusionsoft-php#168]
I'm getting inconsistent results from the addToGroup method in the ContactService.

```
if($infusionsoft->contacts('xml')->addToGroup($contactId, $groupId))
{
   return true;
}
return false;
```

This is a very basic example of what my code check looks like. The problem I'm having is that sometimes it returns false even when I see the update occurred inside InfusionSoft.

I'm referencing: https://developer.infusionsoft.com/docs/xml-rpc/#contact-add-a-tag-to-a-contact which claims to return a boolean value, presumably based on the success of the operation?

Anyone have any suggestions or maybe able clear up any misunderstandings I'm having?

**Comment by brumiser1550** [comment]
Are you sure the tag was not already applied to the contact? If so, I believe that method returns false because the tag is already present.

**Comment by Xavious** [comment]
At first I thought that was a possibility, but I've tested it several times and that is not the problem. I will look at the contact and see that it has a particular tag. I run the script and it reflects the tag changing in Infusionsoft, but the method itself is returning false. It's inconsistent. It doesn't always flag false, but most of the time it seems to and I haven't pinned down a pattern yet.

**Comment by Xavious** [comment]
This is the complete method I am using. It's nested in a try catch block.

```
    /**
     * @param int $contactId
     * @return boolean
     */
    public function updateInfusionsoftStatus($contactId)
    {
        $this->simpleLog("Adding Infusionsoft Contact Id: $contactId to group: $this->infusionsoftStatusId");
        try
        {
            if($this->infusionsoft->contacts('xml')->addToGroup($contactId, $this->infusionsoftStatusId))
            {
                $this->simpleLog("Contact added to group successfully");
                return true;    
            }
        }
        catch(Exception $e)
        {
            $this->simpleLog("EXCEPTION:".$e->getMessage());
            $this->exceptions[] = $e->getMessage();
        }
        $this->simpleLog("Failed to add contact to group");
        return false;
    }
```

**Comment by mfairch** [comment]
@Xavious, @brumiser1550 is correct, it only returns false if the tag is already applied or there was some other exception during the process. 

Have you tried applying the tag via rest? the Rest endpoint returns more info.

https://developer.infusionsoft.com/docs/rest/#!/Contact/applyTagsToContactIdUsingPOST

```
$this->infusionsoft->contacts()->->mock(['id' => 123])->applyTags([$this->infusionsoftStatusId]);
```


If you can duplicate it repeatedly, please open a support ticket with more details, include the app name, a sample contact id, and a sample tag Id.

https://developer.infusionsoft.com/support/tickets/create/

**Comment by Xavious** [comment]
@mfairch Originally it was my desire to use the REST endpoint, but the documentation is extremely vague and I wasn't able to find a working example. I resorted to XML because it was easier to discern the proper syntax, and I think I actually found a code example somewhere.

I noticed in your example you are using the method "applyTags()", but I do not see a reference to this method anywhere inside the SDK. I've tried searching this repository with the GitHub search, and also using grep on my web server, both to no avail. (This example also throws an "undefined method" error). Do you mean to reference addTags() perhaps? Will it add one tag and remove the previous?

Unfortunately most of these REST methods lack comments describing their intent, though some are surmised easily enough at a glance, I suppose.

**Comment by mfairch** [comment]
@Xavious you are correct, it is `addTags()` I didn't double check what it had been called. I have updated my example to be accurate. My example should work, it'll return an array.

**Comment by Xavious** [comment]
@mfairch You got me on the right track to using REST. I'm just going to work on converting my methods into REST calls instead of XML. I'm starting to get a feel for the general structure I think. Your suggestion was mostly correct, but you had a minor typo. It was in fact addTags(). After I changed it to that I got a "SUCCESS" message back in the array, and "DUPLICATE" when I resubmitted it.

Thanks for your response. The working snippet for posterity:

```
$response = $sii->infusionsoft->contacts()->mock(['id' => $contactId])->addTags([$tagId]);
echo "<pre>";print_r($response);echo"</pre>";
die();
```

**Comment by Xavious** [comment]
Okay, so I went ahead and set up REST for this particular problem and don't care to dig any deeper to the underlying cause for why the XML version was causing the return to fail. I'll just chalk it up to a mistake on my part somewhere and consider this closed.

However, as an aside, and maybe for my own growth as a developer, can someone explain to me the logic in returning this response as an array, instead of a string for this REST call? Presumably it should not be returning more than one of these possible responses anyway right?

https://developer.infusionsoft.com/docs/rest/#!/Tags/applyTagToContactIdsUsingPOST
