### ISSUE TITLE
Retrieve an Email

### ISSUE THREAD

**Issue by curious-jim** [infusionsoft/infusionsoft-php#170]
`EmailService` uses `CannotFind` trait, it makes it impossible to retrieve email content by email id

I removed the trait and `find` method works fine. Is it a bug?

**Comment by curious-jim** [comment]
just realised that min-stability was `dev` and the version I was using is `1.4.0-beta`

**Comment by mfairch** [comment]
1.4.0-beta was released before the find endpoint was added. This will be fixed in a future update.

**Comment by curious-jim** [comment]
any updates?
