### ISSUE TITLE
CURL

### ISSUE THREAD

**Issue by blindsz** [infusionsoft/infusionsoft-php#171]
Hi. Just wanted to ask if the latest version of SDK still needs curl to work?

Thanks!

**Comment by mfairch** [comment]
Using Guzzle it should not anymore.

**Comment by blindsz** [comment]
Thanks for the reply 'mfairch'. One more thing when using xml would it use curl or not?

**Comment by mfairch** [comment]
The fxmlrpc library we have using a Guzzle adapter so it shouldn't but I've never tested that specifically.

**Comment by mfairch** [comment]
@blindsz Were you ever able to test this and confirm?
