### ISSUE TITLE
[NoFieldFound]No field found: Contact.given_name

### ISSUE THREAD

**Issue by chris087** [infusionsoft/infusionsoft-php#178]
Hello,

Thanks for this great API contrainer. I have one issue, I try to update a client:

$this->infusionsoft->contacts('xml')->update($cid, $contact); 

I get:

Fatal error:  Uncaught fXmlRpc\Exception\FaultException: [NoFieldFound]No field found: Contact.given_name

(for all fields), this is just one example.

creating a contact works perfect;
$cid = $this->infusionsoft->contacts()->create($contact); 

my contact array:

            $contact = [
             'given_name' => $params['firstname'],
             'middle_name' => $params['middle_name'],
             'family_name' => $params['lastname'],
             'birthday' => $params['birthday'], 
             'prefix' => $params['prefix'],
             'anniversary' => $params['birthday'], 
.....

**Comment by mfairch** [comment]
You are getting that error because you are trying to update a contact using xmlrpc instead of rest. XMLRPC field names are different. 

Give this a try instead.

```php
 $contact = [
         'id' => $cid,
         'given_name' => $params['firstname'],
         'middle_name' => $params['middle_name'],
         'family_name' => $params['lastname'],
         'birthday' => $params['birthday'], 
         'prefix' => $params['prefix'],
         'anniversary' => $params['birthday']
];

$infusionsoft()->contacts()->mock($contact)->save();
```

**Comment by chris087** [comment]
Thx! that worked!

**Comment by sodbpp** [comment]
This mock method needs documentation. I just spent 2hrs trying to properly use the contacts('xml')->update method when the above was actually what I needed.

The disconnect between the documentation, the implemented rest controller methods, and the xml-rpc controller methods is baffling. #ConfusionSoft

**Comment by mfairch** [comment]
@sodbpp We've started documenting model methods in the wiki.

https://github.com/infusionsoft/infusionsoft-php/wiki/Rest-API#mock
