### ISSUE TITLE
Message: [curl] 6: Couldn't resolve host 'api.infusionsoft.com' [url] https://api.infusionsoft.com/token

### ISSUE THREAD

**Issue by merlindiavova** [infusionsoft/infusionsoft-php#18]
It seems alot of issues are being caused due the api.infusionsoft.com being unavailable Any advise on this?
```
Type: Guzzle\Http\Exception\CurlException

Message: [curl] 6: Couldn't resolve host 'api.infusionsoft.com' [url] https://api.infusionsoft.com/token

Filename: /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php

Line Number: 338

Backtrace:

File: /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php
Line: 279
Function: isCurlException

File: /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php
Line: 244
Function: processResponse

File: /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php
Line: 227
Function: processMessages

File: /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php
Line: 211
Function: executeHandles

File: /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php
Line: 105
Function: perform

File: /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMultiProxy.php
Line: 91
Function: send

File: /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Client.php
Line: 282
Function: send

File: /home/zae/app/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php
Line: 198
Function: send

File: /home/zae/app/vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/GuzzleClient.php
Line: 35
Function: send

File: /home/zae/app/vendor/infusionsoft/php-sdk/src/Infusionsoft/Infusionsoft.php
Line: 266
Function: request

File: /home/zae/app/_a/libraries/Infusionsoft.php
Line: 101
Function: refreshAccessToken

File: /home/zae/app/_a/libraries/Infusionsoft.php
Line: 73
Function: _refreshTokenWithAction

File: /home/zae/app/_a/libraries/Infusionsoft.php
Line: 49
Function: _execute

File: /home/zae/app/_a/controllers/admin/Forms/View.php
Line: 24
Function: getWebform

File: /home/zae/app/public/index.php
Line: 309
Function: require_once 
```

**Comment by micfai** [comment]
Couldn't resolve host 'api.infusionsoft.com' means that your dns server cannot resolve the domain name. I would check with your provider to figure out what happened there.

**Comment by merlindiavova** [comment]
That's I what i though initially but when i switch from Guzzle to the CurlClient its a go. Not entirely sure what to make of it

**Comment by micfai** [comment]
@merlindiavova that is interesting that it doesn't happen with the CurlClient. @kressaty have any ideas on this one?

**Comment by kressaty** [comment]
My first thought is around the time between switching - @merlindiavova when you switch back, does it stop working again? Or could it have just been a hiccup in DNS from your local network connection?

**Comment by merlindiavova** [comment]
I has not happened since my last post. Let me monitor this and report back next week

**Comment by merlindiavova** [comment]
The problem still exists months later although not as often

So basically once a token has been obtained. Make a api call and then reload the same page and you get connection errors reload again then the token you obtained is complete invalid and you have to obtain a new one.

**Comment by kressaty** [comment]
Can you reproduce it? If so, can you run the request through Runscope and email me the public link to that request?

**Comment by kressaty** [comment]
@merlindiavova I'm going to close this out; we haven't had any more reports and haven't heard back from you. if it does occur again, hit up the support email / form and someone will get back to you ASAP: https://developer.infusionsoft.com/support/tickets/create/

**Comment by ryrobbo** [comment]
Apologies for resurrecting an old issue but I ran into this issue today on Ubuntu 16, PHP 7.1.

I managed to resolve it by adding a host to my server's host file:

    184.169.175.116    api.infusionsoft.com
