### ISSUE TITLE
Query not working for the new integrations

### ISSUE THREAD

**Issue by aksteps** [infusionsoft/infusionsoft-php#187]
I have been using query to fetch input fields of a contact using code:
` $fields = $this->infusionsoft
			->data
			->query('DataFormField', 1000, 0, ['FormId' => '-1'],
        ['Id', 'DataType', 'DefaultValue', 'FormId', 'GroupId', 'Label', 'ListRows', 'Name', 'Values'],
        'Id',
        false);`
This works fine for old integrations but doesn't give me anything on new integrations.

**Comment by mfairch** [comment]
DataFormField only contains Custom Fields for the application so it's possible that an application doesn't have any custom fields yet.
