### ISSUE TITLE
REST API - Deleting a File

### ISSUE THREAD

**Issue by ajohnson6494** [infusionsoft/infusionsoft-php#192]
Currently there is an issue with deleting a file using the REST api. 

I believe the issue is related to `$this->{$this->primaryKey}` because the primaryKey `id` is not defined here. it is at `$this->file_descriptor['id']`

**Comment by ajohnson6494** [comment]
Example code to reproduce bug.

`Infusionsoft::files()->find($fileId)->delete()`

**Comment by skeemer** [comment]
I think this can be closed now.
