### ISSUE TITLE
setAttribute is public but not documented

### ISSUE THREAD

**Issue by whitebyte** [infusionsoft/infusionsoft-php#194]
Each object retrieved from the API has a method called `setAttribute` (along with `getAttribute` and a couple of others) that is marked as "public" but not documented. Should this method be used an in what cases?

**Comment by skeemer** [comment]
The methods setAttribute and getAttribute on the REST APIs are used by the magic setter/getters.

`$contact->given_name` is `$contact->getAttribute('given_name')`
`$contact->given_name = 'first'` is `$contact->setAttribute('given_name', 'first')`

You can use them if you want, but $item->field gives you the exact same and usually makes readability easier.
