### ISSUE TITLE
opportunity->save() results in 405 "method not allowed" error

### ISSUE THREAD

**Issue by whitebyte** [infusionsoft/infusionsoft-php#195]
```php
$opportunity = $infusionsoft->opportunities()->create([
    'opportunity_title' => 'whatever'
    'opportunity_notes' => 'whatever',
    'stage' => [
        'id' => 123
    ]
]);
// so far so good, the opportunity created succesfully

$opportunity->user = [
    'id' => 1
];

$opportunity->save(); // oops, got Infusionsoft\Http\HttpException

```

Client error: `PUT https://api.infusionsoft.com/crm/rest/v1/opportunities/123?access_token=123` resulted in a `405 Method Not Allowed` response

Related forum topic: https://community.infusionsoft.com/t/not-able-to-map-user-to-opportunity-through-api/24795/8

**Comment by whitebyte** [comment]
It seems that opportunities can be updated using PATCH instead of PUT. At least if we look at the official REST docs we'll notice that they utilize PATCH: https://developer.infusionsoft.com/docs/rest/#!/Opportunity/updatePropertiesOnOpportunityUsingPATCH. Yet if we look at https://github.com/infusionsoft/infusionsoft-php/blob/c0efd6d290d062b0bae10abc5c88c01b8f447466/src/Infusionsoft/Api/Rest/RestModel.php#L165 we'll see that POST and PUT are the only available options for PHP SDK. Even more interesting, if we change the method to PATCH manually, it kinda works... but only if we provide a correct and existing `affiliate_id`! If before the `save()` method invocation `affiliate_id` is not set for whatever reason, the request will fail with `400 Bad Request response: {"message":"Affiliate Id is invalid"}` error.

What a mess. Could we have this addressed anytime soon?

**Comment by mfairch** [comment]
Fixed by #212

**Comment by skeemer** [comment]
As a followup to the comment about affiliate_id, I've filed a bug report with the API team. We should be able to save back the exact same data we pulled. `unset $opportunity->affiliate_id;` does work in the meantime.

**Comment by skeemer** [comment]
I'm not sure if the maintenance release has run yet, but a fix is in the most recent or next release.

"Our developers decided that the least disruptive change would be to allow "0" to pass validation when used for affiliate_id in the PATCH and POST /opportunities endpoints."
