### ISSUE TITLE
How do you create a new blank Invoice and add Manual Payment?

### ISSUE THREAD

**Issue by crazyserb** [infusionsoft/infusionsoft-php#208]
I've looked at the DataService.php and InvoiceService.php and it seems like something like this SHOULD be allowed but I am getting errors saying it's not:

$order = array(
	'contactID' => $contactIDNumber,
	'name' => $ORDER_DESC,
	'orderDate' => $datetime,
	'leadAffiliateID' => '0',
	'saleAffiliateID' => '0',
);
$invoiceIDNumber = $infusionsoft->data()->add('Invoice', $order);
$update = $infusionsoft->invoices->addManualPayment($invoiceIDNumber, $order_total, $datetime, $payment_type, $payment_desc, 0);

Any suggestions on how to do this?

Just need to add a blank invoice and then a manual payment to it, as all payments are done outside of InfusionSoft, just need a record of them in there.

Please help!

**Comment by crazyserb** [comment]
This is what I am getting in terms of errors:

[NoTableAccess]Access denied to table Invoice

/vendor/infusionsoft/php-sdk/src/Infusionsoft/Api/DataService.php(14): Infusionsoft\Infusionsoft->request('DataService.add', 'Invoice', Array) #5 /public_html/infusionsoft2.php(160): Infu in /vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/InfusionsoftSerializer.php on line 34

**Comment by mfairch** [comment]
@crazyserb use https://developer.infusionsoft.com/docs/xml-rpc/#invoice-create-an-invoice instead. Once the blank invoice is created, you can then use https://developer.infusionsoft.com/docs/xml-rpc/#invoice-add-an-item-to-an-invoice to add items.

I would also look at using REST instead of xmlrpc.

https://developer.infusionsoft.com/docs/rest/#!/E-Commerce/createOrderUsingPOST

**Comment by crazyserb** [comment]
Ok, well how do I do that within this framework?

I am looking at the XML-RPC docs, following everything to the tee, and yet I can't get it working.

I pass this in one line:

$orderIDNumber = $infusionsoft->invoices->createBlankOrder($contactIDNumber, $orderDesc, $datetime, 0, 0);

and it works, it creates an empty order.

and then in the next line I pass this:

$update = $infusionsoft->invoices->addOrderItem($orderIDNumber, 1, 4, 199.99, 1, $payment_description, $payment_notes);

and it throws this:

Fatal error: Uncaught Infusionsoft\Http\HttpException: fXmlRpc\Exception\FaultException: No method matching arguments: java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String in /vendor/lstrojny/fxmlrpc/src/fXmlRpc/Exception/FaultException.php:32 Stack trace: #0 /vendor/lstrojny/fxmlrpc/src/fXmlRpc/Parser/XmlReaderParser.php(373): fXmlRpc\Exception\FaultException::fault(Array) #1 /vendor/lstrojny/fxmlrpc/src/fXmlRpc/Client.php(153): fXmlRpc\Parser\XmlReaderParser->parse('<?xml version="...') #2 /vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/InfusionsoftSerializer.php(28): fXmlRpc\Client->call('InvoiceService....', Array) #3 /vendor/infusionsoft/php-sdk/src/Infusionsoft/Infusionsoft.php(404): Infusionsoft\Http\InfusionsoftSerializer->request('InvoiceService....', 'https://api.inf...', Array, Object(fXmlRpc\Client)) #4 /vendor/infusionsoft/php-sdk/src/Infusionsoft/Api/InvoiceSe in /vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/InfusionsoftSerializer.php on line 34

What am I supposed to make out of that?

I'm using the exact method / parameters defined in this package:

public function addOrderItem($invoiceId, $productId, $type, $price, $quantity, $description, $notes)

so what am I missing?

**Comment by mfairch** [comment]
No method matching arguments means that a data type is off. We can figure out which one fairly easily by comparing this line to the docs.
`java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String`

The docs show it should be `String, Integer, Integer, Integer, Double, Integer, String, String`. In this case PHP casted your price to an integer instead of a double (float).

Give this a try

```php
$update = $infusionsoft->invoices->addOrderItem($orderIDNumber, 1, 4, (float) 199.99, 1, $payment_description, $payment_notes);

**Comment by crazyserb** [comment]
Hmm, that worked... along with me casting a few other parameters as quoted strings and such.

Thanks for pointing me in the right direction, as I wasn't sure what was happening...
