### ISSUE TITLE
How to make batch update for contacts custom field

### ISSUE THREAD

**Issue by devashish-laitkor** [infusionsoft/infusionsoft-php#218]
Hi,

I want to make a batch update for a custom fields.
Currently we are updating under foreach loop, but it takes long time (3-4 min) to update.

```
 $contacts = Infusionsoft_DataService::query(new Infusionsoft_Contact(), array('Groups' => $group_id));
foreach ($contacts as $contact) {
     $contact->_AdditionalComments = $comment;
     $contact->save();
} 
```

**Comment by devashish-laitkor** [comment]
Any update ?

**Comment by mfairch** [comment]
@devashish-laitkor there are not batch endpoints in the API so you have to do it one at a time.
