### ISSUE TITLE
SubscriptionPlan missing # of Cycles field in the API

### ISSUE THREAD

**Issue by jwondrusch** [infusionsoft/infusionsoft-php#22]
When working with a Subscription Plan via the app, there is a field for # of Cycles that is inaccessible via the API.  This needs to be supported for being able to fully integrate with Infusionsoft via the API in any app that is offering remote creation of products that want to use Subscriptions w/ an expiration date.

**Comment by micfai** [comment]
This isn't an actual issue with this SDK. The API just doesn't provide the information. Closing as not an actual issue with this sdk.

**Comment by jwondrusch** [comment]
Closing makes sense, but is there any plan to expose that field via the API and a timeline for doing so?  According to the Infusionsoft developer forums, this has been a known issue for > 15 months.

**Comment by micfai** [comment]
Its up to Product Management to decide to open it up.

**Comment by jwondrusch** [comment]
Any way to communicate with them about it?
