### ISSUE TITLE
{"error":"invalid_grant","error_description":"Invalid refresh token"}

### ISSUE THREAD

**Issue by mrkdnllw** [infusionsoft/infusionsoft-php#228]
Hello, I'm testing infusionsoft sdk on xampp(still trying to learn how to use it). I have this code: 

`<?php if(empty(session_id())) session_start();

require_once 'vendor/autoload.php';

$infusionsoft = new \Infusionsoft\Infusionsoft(array(
	'clientId'     => 'clientid',
	'clientSecret' => 'clientsecret',
	'redirectUri'  => 'http://localhost:81/infusionsoft-test/',
));

// If the serialized token is available in the session storage, we tell the SDK
// to use that token for subsequent requests.
if (isset($_SESSION['token'])) {
	$infusionsoft->setToken(unserialize($_SESSION['token']));
}

// If we are returning from Infusionsoft we need to exchange the code for an
// access token.
if (isset($_GET['code']) and !$infusionsoft->getToken()) {
	$_SESSION['token'] = serialize($infusionsoft->requestAccessToken($_GET['code']));
}
$infusionsoft->refreshAccessToken();
    //$token = $infusionsoft->getToken();
if ($infusionsoft->getToken()) {
	// Save the serialized token to the current session for subsequent requests
	$_SESSION['token'] = serialize($infusionsoft->getToken());
	echo "authorisation success<br>";
	// MAKE INFUSIONSOFT REQUEST
} else {
	echo '<a href="' . $infusionsoft->getAuthorizationUrl() . '">Click here to authorize</a>';
}

$infusionsoft->contacts('xml')->add(array('FirstName' => 'Test1', 'LastName' => 'Test1'));
?>`

in my index.php, however, I get this error:

( ! ) Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://api.infusionsoft.com/token` resulted in a `400 Bad Request` response: {"error":"invalid_grant","error_description":"Invalid refresh token"} in C:\xampp\htdocs\infusionsoft-test\vendor\infusionsoft\php-sdk\src\Infusionsoft\Http\GuzzleHttpClient.php on line 74
--

1 | 0.3184 | 389160 | {main}( ) | ...\index.php:0
2 | 0.3421 | 856160 | Infusionsoft\Infusionsoft->refreshAccessToken( ) | ...\index.php:22
3 | 0.3602 | 1317168 | Infusionsoft\Http\GuzzleHttpClient->request( ) | ...\Infusionsoft.php:318

I have tried to search for answers on the web and on community forum but couldn't find any. Any help is greatly appreciated. Thank you!

**Comment by pagedesigner** [comment]
First of all you should not share your APP secret, use following code:

`<?php if(empty(session_id())) session_start();

require_once 'vendor/autoload.php';

$infusionsoft = new \Infusionsoft\Infusionsoft(array(
'clientId' => '24rftrghvg5gwffmqfvk7fxv',
'clientSecret' => 'vg4VVkWgcq',
'redirectUri' => 'http://localhost:81/infusionsoft-test/',
));

// If the serialized token is available in the session storage, we tell the SDK
// to use that token for subsequent requests.
if (isset($_SESSION['token'])) {
	$infusionsoft->setToken(unserialize($_SESSION['token']));
    $conID = $infusionsoft->contacts('xml')->add(array('FirstName' => 'Test1', 'LastName' => 'Test1'));
    print_r($conID);
}

// If we are returning from Infusionsoft we need to exchange the code for an
// access token.
if (isset($_GET['code']) and !$infusionsoft->getToken()) {
	$_SESSION['token'] = serialize($infusionsoft->requestAccessToken($_GET['code']));
}

if ($infusionsoft->getToken()) {
	// Save the serialized token to the current session for subsequent requests
	$_SESSION['token'] = serialize($infusionsoft->getToken());

	// MAKE INFUSIONSOFT REQUEST
} else {
	echo '<a href="' . $infusionsoft->getAuthorizationUrl() . '">Click here to authorize</a>';
}
?>`

**Comment by ajohnson6494** [comment]
Here is a little more details around how to setup Infusionsoft https://github.com/ajohnson6494/infusionsoft-php/wiki/Server-to-Server-Communication

**Comment by scamexdotexe** [comment]
I am having the same issue. I just used the sample code and I am saving the token (serialized to db) and unserialized it when setting the token in the infusionsoft instance so there's no way the tokens be modified.

```
if(!empty($user['itoken'])){
			$itoken = $user['itoken'];
				$infusionsoft->setToken(unserialize($user['itoken']));
				$tokentime = $infusionsoft->isTokenExpired();
				if($tokentime){

					var_dump($infusionsoft->getToken());

					$infusionsoft->refreshAccessToken();		//request to refresh access token
					$ntoken = $infusionsoft->getToken();		//get the token
					$srtoken = serialize($ntoken);					//serialize for db

					$tokens = json_decode(json_encode($ntoken), true);
					$endoflife = $tokens['endOfLife'];

					$tokens = $db->prepare("UPDATE users SET itoken = ?, iendoflife = ?  WHERE id = ?");
		 		  $tokens->execute([$ntoken, $endoflife, $user['id']]);
				}
	}
```

Any other ideas on how to solve this?

**Comment by pagedesigner** [comment]
Try this
`// retrieve the existing token object from storage
$infusionsoft->setToken($yourStoredToken);  //try without unserialize()

$infusionsoft->refreshAccessToken();`
