### ISSUE TITLE
node / JS API?

### ISSUE THREAD

**Issue by dcsan** [infusionsoft/infusionsoft-php#23]
guess this isn't the best place to ask, but i've looked around...
is there a nodeJS or javascript API anywhere?

i guess you don't expose anything client side, is that correct?

**Comment by kressaty** [comment]
No official lib, but there's nothing stopping you from making direct xmlrpc requests. Quick googling came up with https://github.com/baalexander/node-xmlrpc which looks promising, and you should be able to get the full power of the API with relatively low overhead. I'm not super familiar with OAuth and Node, but I'd imagine that shouldn't be too difficult either.
