### ISSUE TITLE
Sending email feature ready for production ?

### ISSUE THREAD

**Issue by pneftali** [infusionsoft/infusionsoft-php#24]
Is the latest version usable for production ? I only need the send email functionality for now.
The https://github.com/infusionsoft/PHP-iSDK no longer works for sending out emails.
If not, can we get the eta for when the stable php sdk will be out.

Thanks

**Comment by kressaty** [comment]
The new PHP SDK is in a stable state, and you should have no problem sending an email from it (or from the iSDK afaik).
