### ISSUE TITLE
oauth2 authorization error

### ISSUE THREAD

**Issue by mrkdnllw** [infusionsoft/infusionsoft-php#254]
Good day!

I'm trying to set up my app for Infusionsoft rest api oauth2. 

I get the following URL when doing an rest authorization:

https://localhost:44336/?error=server_error
&error_uri=https%3A%2F%2Fdeveloper.infusionsoft.com%2Fdocs%2Fread%2FGetting_Started_With_OAuth2
&error_description=An+error+occurred

I requested the authorization using this url: https://signin.infusionsoft.com/app/oauth/authorize?client_id=6540adac-8892-4de5-812b-847b7092aeb5&redirect_uri=https://localhost:44336/&response_type=code&scope=full

The Infusionsoft account email is different from my infusionsoft developer email. Do they have to be the same for it to work?

Any help is greatly appreciated. Thanks!

**Comment by ajohnson6494** [comment]
I think you are using your app id instead of the client_id.

<img width="811" alt="Screen Shot 2020-04-24 at 7 19 12 PM" src="https://user-images.githubusercontent.com/5192820/80264056-c0550080-8660-11ea-8ff9-7057175e8172.png">

**Comment by mrkdnllw** [comment]
thank you so much for responding. yes, it was the app id lol. i changed it. thank you so much!
