### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by thehelvetian** [infusionsoft/infusionsoft-php#258]
Any plans on merging the outstanding PR's and generally keeping the SDK a bit more up-to-date?

**Comment by ajohnson6494** [comment]
@thehelvetian Keap is discussing this internal. They currently don't have anyone focused on this repo right now. They are debating on whether or not they want to allow the community to maintain this repo. I hope that they get something done soon as issues and PR's are piling up. :)

**Comment by thehelvetian** [comment]
Thank you for the insight @ajohnson6494. The community already has the ability to contribute to the repo via PRs. It just needs a dedicated maintainer and I think Keap should provide that to assure quality & integrity.

**Comment by bbooth** [comment]
Our API Team has officially started to own this repo.  We are merging in old PRs this week.  Look for a new release shortly.
