### ISSUE TITLE
Some services work, some don't

### ISSUE THREAD

**Issue by upwebdesign** [infusionsoft/infusionsoft-php#26]
I am hoping I can get some answers/suggestions with this issue I am having with the API. For example, I am able to "load" a contact and get contact fields, no problem. I can "search" saved searches from the API, awesome. BUT, when I try to use the "AffiliateService" OR "AffiliateProgramService "methods, an exception is thrown.

Sample call: 
`$infusionsoft->affiliates()->affPayouts(xxxxx, Carbon::now()->subMonth(), Carbon::now());`

Results in:

> HttpException in InfusionsoftSerializer.php line 34:

> exception 'fXmlRpc\Exception\ResponseException' with message 'No such handler: AffiliateService.affPayouts'

This is the case for ALL AffiliateService methods. There must be something I am not quite understanding, or is the API incomplete? We are supposed to pass dateTime objects into the methods, correct?

It seams as though the handler is named incorrectly...

Thanks for any guidance!

**Comment by micfai** [comment]
The handler was named incorrectly. Its supposed to be APIAffiliateService but we'll handle that on the backend so you don't have to change any code to use it.

I verified the AffiliateProgramService works though.

**Comment by upwebdesign** [comment]
Thanks for the quick response, sorry about my late response, I did not get notification of your response and stumbled upon it just now.

**Comment by upwebdesign** [comment]
OK, finally had a chance to test this out. Composer updated to the latest fix. Now, all I get is a white screen of death. No PHP errors in logs, just a white screen.

**Comment by upwebdesign** [comment]
Found this in my log:

Fatal error: Class undefined: \\Infusionsoft\\Api\\AffiliateService in /vendor/infusionsoft/php-sdk/src/Infusionsoft/Infusionsoft.php on line 567

**Comment by upwebdesign** [comment]
Confirmed this fixed the problem:

class APIAffiliateService extends AbstractApi {

should be

class AffiliateService extends AbstractApi {

**Comment by upwebdesign** [comment]
This is my attempt to use Affiliate Program Service (AffiliateProgramService):

`Infusionsoft::affiliatePrograms()->getProgramsForAffiliate((int)xxxxx);`

This is what I get:

>HttpException in InfusionsoftSerializer.php line 34:
exception 'fXmlRpc\Exception\RuntimeException' with message 'Invalid XML. Expected one of "string", "array", "struct", "int", "biginteger", "i8", "i4", "i2", "i1", "boolean", "double", "float", "bigdecimal", "dateTime.iso8601", "dateTime", "base64", "nil", "dom", "#text", got "value" on depth 9 (context: "<value/>")' in /vendor/lstrojny/fxmlrpc/src/fXmlRpc/Exception/RuntimeException.php:41

**Comment by upwebdesign** [comment]
How did you verify AffiliateProgramService is working? Every time I try it does not work...

**Comment by micfai** [comment]
The XML that is being sent back isn't being parsed right for you. Issue #3 is what you are experiencing now.

**Comment by upwebdesign** [comment]
Im confused, what am I supposed to do if the XML that is being sent back to me isn't being parsed correctly? Obviously `getAffiliatePrograms()` does not accept any arguments for me to miss "type" a value, yet I still get the exception. The reference to issue #3 has to do with saved searches. Standing by.

**Comment by micfai** [comment]
#3 was reported with Saved Searches but affects more than just Saved Searches. Take a look at the issue on fxmlrpc https://github.com/lstrojny/fxmlrpc/issues/36

**Comment by upwebdesign** [comment]
Thanks for pointing that out. Your composer.json file is pulling in release "lstrojny/fxmlrpc": "0.8.*", which I assume does not have the fxmlrpc lstrojny/fxmlrpc#36 fix in it. It looks like it failed: https://github.com/lstrojny/fxmlrpc/compare/0.8.3...master Am I reading this correctly?

**Comment by upwebdesign** [comment]
So, is this my issue because Im not sure what direction I need to take to solve this problem.
