### ISSUE TITLE
How do I set the Reply-To: header?

### ISSUE THREAD

**Issue by JasonWoof** [infusionsoft/infusionsoft-php#262]
I'm sending emails via the APIEmailService.sendEmail xml api call documented here: https://developer.infusionsoft.com/docs/xml-rpc/#email-send-an-email

How do I set the `Reply-To:` header?

Thanks!

**Comment by JasonWoof** [comment]
As SPF and DKIM become more common, it becomes more and more important to be able to set Reply-To separately.

Can this serve as a feature request? Or is there a better place for one?

**Comment by ajohnson6494** [comment]
Unfortunately, this is not a feature that this repo can implement, as it does not control Infusionsoft's backend systems. If Infusionsoft decides to implement this feature through their api, then we can implement that new endpoint in this repo.

I would recommend reaching out to [Infusionsoft support](https://help.infusionsoft.com/help/contact-support) or posting in the [community forums](https://community.infusionsoft.com/) with this feature request.

Some other helpful resources regarding SPF and DKIM with Infusionsoft.
- [Configure your SPF records](https://help.infusionsoft.com/help/configure-your-spf-records)
- [Configure your DKIM records](https://help.infusionsoft.com/help/dkim)

**Comment by JasonWoof** [comment]
OK, thanks. I've asked the infusionsoft account holder in my organization to make a support ticket.
