### ISSUE TITLE
Release 1.5.0 erroring with Guzzle6 not found

### ISSUE THREAD

**Issue by Ultimater** [infusionsoft/infusionsoft-php#270]
See issue https://github.com/infusionsoft/infusionsoft-php/issues/269
Caused by incomplete code merged here: https://github.com/infusionsoft/infusionsoft-php/issues/264

I tried running latest laravel with Release 1.5.0
When I try to use it, I get an error:

Class 'Http\Adapter\Guzzle6\Client' not found

Shouldn't have made a release without testing it...
This is a major issue that has broken the code.

**Comment by Ultimater** [comment]
This was fixed with the 1.5.1 release.

**Comment by bbooth** [comment]
Thanks for the PR!
