### ISSUE TITLE
How do I find my clientid and clientSecret?

### ISSUE THREAD

**Issue by markarupert** [infusionsoft/infusionsoft-php#280]
How do I find my clientid and clientSecret for this below?
Is it my appid and the encrypted key?

	$infusionsoft = new \Infusionsoft\Infusionsoft(array(
	'clientId'     => 'XXXXXXXXXXXXXXXXXXXXXXXX',
	'clientSecret' => 'XXXXXXXXXX',
	'redirectUri'  => 'http://example.com/',
	));

**Comment by bbooth** [comment]
Please reach out to https://community.infusionsoft.com under the API topic.  That is our main place for support.  Long story short though is you need to register as a developer at https://developer.infusionsoft.com to get your OAuth client credentials.  The site also has lots of docs what you need to do.

**Comment by markarupert** [comment]
Thanks
