### ISSUE TITLE
AffiliateService HttpException

### ISSUE THREAD

**Issue by upwebdesign** [infusionsoft/infusionsoft-php#29]
I am creating a new issue as my other ticket was out of scope with the issue I (and others) am experiencing.

This is my attempt to use Affiliate Program Service (AffiliateProgramService):

Infusionsoft::affiliatePrograms()->getProgramsForAffiliate((int)xxxxx);
Infusionsoft::affiliatePrograms()->getAffiliatePrograms();

This is what I get:

> HttpException in InfusionsoftSerializer.php line 34:
exception 'fXmlRpc\Exception\RuntimeException' with message 'Invalid XML. Expected one of "string", "array", "struct", "int", "biginteger", "i8", "i4", "i2", "i1", "boolean", "double", "float", "bigdecimal", "dateTime.iso8601", "dateTime", "base64", "nil", "dom", "#text", got "value" on depth 9 (context: "")' in /vendor/lstrojny/fxmlrpc/src/fXmlRpc/Exception/RuntimeException.php:41

This was referenced to issue Invalid XML error https://github.com/infusionsoft/infusionsoft-php/issues/3 then this issue was reference with fxmlrpc https://github.com/lstrojny/fxmlrpc/issues/36 by which my response was:

> Thanks for pointing that out. Your composer.json file is pulling in release "lstrojny/fxmlrpc": "0.8.*", which I assume does not have the fxmlrpc lstrojny/fxmlrpc#36 fix in it. It looks like it failed: https://github.com/lstrojny/fxmlrpc/compare/0.8.3...master Am I reading this correctly?

I am stuck on what to do because infusionsoft-php owns the dependency and I am not keen on forking the project. Is this issue something Infusionsoft can address or not? Any sort of response will be helpful.

Respectfully

**Comment by kressaty** [comment]
FYI there are a bunch of discussions happening around this; I'm going to try and have something else in terms of info for you today, as we do know this is a major pain point and we want to get it fixed ASAP.

**Comment by micfai** [comment]
We just pushed a fix for this to the develop branch. Please note: due to the fix in the fxmlrpc library, it now requires PHP 5.4 as a minimum requirement to use it. 
 
Please see commit f6c582aef7e486d304933d48f556374cda4ba117
