### ISSUE TITLE
Invalid XML error

### ISSUE THREAD

**Issue by graphem** [infusionsoft/infusionsoft-php#3]
I often get this kind of issue when using the search module with saved search:
search->getSavedSearchResults

Fatal error: Uncaught exception 'Infusionsoft\InfusionsoftException' with message 'Invalid XML. Expected one of "string", "array", "struct", "int", "biginteger", "i8", "i4", "i2", "i1", "boolean", "double", "float", "bigdecimal", "dateTime.iso8601", "dateTime", "base64", "nil", "dom", "#text", got "value" on depth 9 (context: "<value/>")' in  \infusionsoft-php\src\Infusionsoft\Infusionsoft.php on line 350

So I am not sure if this is caused by Infusionsoft API or the data that is returned. Is there any way to deal with this? Seems to occur only on special fields. E.g.: I have a saved search on Credit Card report and the error occurs when the field Exp is in the fields return array (which is the expiration date string field).

**Comment by skeemer** [comment]
Is this related to this temp fix from @micfai ?
https://gist.github.com/micfai/26db39be03109a051f38#file-xmlreaderparser-php-L152

**Comment by lawfilm** [comment]
I'm getting the same error when I add someone to a campaign through the funnelservice but the call is being made correctly and is successful. 

So I'm getting a fatal error even though the process is working fine. 

Fatal error: Uncaught exception 'Infusionsoft\Http\HttpException' with message 'exception 'fXmlRpc\Exception\RuntimeException' with message 'Invalid XML. Expected one of "string", "array", "struct", "int", "biginteger", "i8", "i4", "i2", "i1", "boolean", "double", "float", "bigdecimal", "dateTime.iso8601", "dateTime", "base64", "nil", "dom", "#text", got "value" on depth 9 (context: "<value/>")' in /var/www/html/fuel/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Exception/RuntimeException.php:33 Stack trace: #0 /var/www/html/fuel/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Parser/XmlReaderParser.php(81): fXmlRpc\Exception\RuntimeException::unexpectedTag('value', Array, 9, '<value/>') #1 /var/www/html/fuel/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Client.php(159): fXmlRpc\Parser\XmlReaderParser->parse('<?xml version="...', false) #2 /var/www/html/fuel/vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/InfusionsoftSerializer.php(28): fXmlRpc\Client->call('FunnelService.a...', Array) #3 /var/www/html/fuel/vendor/infusionsoft/php-sdk/src/Infusionsoft in /var/www/html/fuel/vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/InfusionsoftSerializer.php on line 34

Ideas?

**Comment by safoo** [comment]
+1 on this issue. I receive the same XML error on a getSavedSearchResults call when a returned column has an empty value.

**Comment by lawfilm** [comment]
This seems to be an issue with the conversion to java from a weakly typed language like php... Make sure your values are the exact type the API is expecting.

**Comment by micfai** [comment]
We just pushed a fix for this to the develop branch. Please note: due to the fix in the fxmlrpc library, it now requires PHP 5.4 as a minimum requirement to use it.

Please see commit f6c582aef7e486d304933d48f556374cda4ba117
