### ISSUE TITLE
Refresh Token being refused

### ISSUE THREAD

**Issue by tl8roy** [infusionsoft/infusionsoft-php#30]
After doing some troubleshooting with this [issue](http://community.infusionsoft.com/showthread.php/19199-invalid_client-on-Token-Refresh), I traced the issue to the layout of the refresh function.

The OAuth spec says the client_id and secret should be in POST params. By moving them there, I got the function to work.

    public function refreshAccessToken()
    {
        $params = array(
            'client_id' => $this->clientId,
            'client_secret' => $this->clientSecret,
            'grant_type'    => 'refresh_token',
            'refresh_token' => $this->getToken()->getRefreshToken(),
        );
        $client = $this->getHttpClient();

        $tokenInfo = $client->request($this->tokenUri, $params, array(), 'POST');

        $this->setToken(new Token($tokenInfo));

        return $this->getToken();
    }

This only worked for my case so I don't know if this is a real issue or just my circumstances.

**Comment by leek** [comment]
I am experiencing this same issue - although, just making the change above does not resolve anything for me.

**Comment by kressaty** [comment]
Are you positive you're storing the token in such a way that you can then retrieve it and rebuild into an infusionsoft token object? There are no problems with that function or the handshake at this time. One common problem is storing the token directly without serializing before putting into storage; can you post a more complete example?

To be clear, you should not have to modify any token functions in the SDK for it to work properly.

**Comment by tl8roy** [comment]
I am 100% sure that I am serializing the token correctly (I don't have access to the example at the moment). I had several other issues that were being caused by that problem but those are now resolved. We serialize and Base64 encode going in and Base64 decode and unserialize coming out of the DB.

I also traced through the parameters being passed in the function, and those are also correct. What stuck me as odd is that the basic (header) auth is not used anywhere else. As I said previously, I looked at other OAuth implementations and they all had the client_id and secret in the POST vars and not the header. I basically tried it (As I was out of other options) and it seems to work.

**Comment by kressaty** [comment]
I wonder if the driver is causing the issue; are you using Guzzle or the Curl client? When you make a request with the SDK off the shelf, can you provide the error message and/or a Runscope traffic inspector log?

**Comment by tl8roy** [comment]
Ahh, I forgot to add that I am using the curl client. I am on holidays at the moment, so I can't provide anything for about a week.

**Comment by kressaty** [comment]
No problem - let me try and recreate it later with the Curl client; I'm wondering if that's causing an issue somewhere.

**Comment by tl8roy** [comment]
This is the raw error message from the Curl Client: `{"error":"invalid_client"}`

**Comment by kressaty** [comment]
@tl8roy do me a favor; grab the hotfix/curl-headers branch and give it a shot sans-modification. It's working well for me (and I did successfully recreate your scenario when using curl). If that branch is gone by the time you see this, it'll have been merged into develop (this does require PHP 5.4 at this point)

**Comment by tl8roy** [comment]
I'll see what I can do. I am trying to get this deployed so I have removed the easy way to test it.

**Comment by tl8roy** [comment]
That seems to have worked.

**Comment by tl8roy** [comment]
Is it now 5.3 compatible? I know we were running 5.3 in production last time I checked, but that may have changed.

**Comment by kressaty** [comment]
No - this fix bumps up to 5.4. Let me see if we can get this fixed in the 5.3 version.

**Comment by micfai** [comment]
@tl8roy check out the 5.3 branch which has the fixed @kressaty mentions.

https://github.com/infusionsoft/infusionsoft-php/tree/5.3

**Comment by tl8roy** [comment]
@micfai How can I get that through composer?

**Comment by micfai** [comment]
I tagged a release with it, 1.0.0

**Comment by kressaty** [comment]
Closing as this has been shipped.

**Comment by cyberwombat** [comment]
Can you elucidate on what issue was? I am trying to connect to the APi using Node and am getting the same 'invalid_client' error. I am using Axios.

**Comment by kressaty** [comment]
This is 100% a PHP thread, so your Node issue will be related to not properly storing a token, or not using the correct client ID or secret.
