### ISSUE TITLE
How to retrieve custom fields with XML-RPC? Everything I've tried failed so far.

### ISSUE THREAD

**Issue by crazyserb** [infusionsoft/infusionsoft-php#311]
I can get regular Contact fields like this just fine:

`$ID = 12345;
$cid = $infusionsoft->contacts('xml')->load($ID, ['Email', 'FirstName', 'LastName'])`

But adding any of my custom fields into the array breaks this call altogether.

so this doesn't work at all:

`$cid = $infusionsoft->contacts('xml')->load($ID, ['Email', 'FirstName', 'LastName', 'CustomField1', 'CustomField2'])` (obviously for custom fields with those names/titles)

How can we do this via XML-RPC call, if it's even possible with the current code in place?

Thanks!

**Comment by bbooth** [comment]
Closing as I will answer in the community post you made.
