### ISSUE TITLE
XML Parsing Errors in search->getSavedSearchResults

### ISSUE THREAD

**Issue by cguweb-com** [infusionsoft/infusionsoft-php#339]
no matter what I try, error always complains, as does any other parser I've tried:

Invalid XML. Expected XML, string given: "<?xml version="1.0" encoding="UTF-8"?><methodResponse><params><param><value><array><data>.....

**Comment by bbooth** [comment]
Please open a developer support ticket.  https://developer.infusionsoft.com/get-support/

**Comment by cguweb-com** [comment]
FYI, turned out to be encoded emoji icons in the data, corrupting the XML - haven't found a fix yet, but most parsers are going to choke on this, so I think its on infusionsoft to fix - I will contact them next.  Thanks.
