### ISSUE TITLE
vendor/autoload.php

### ISSUE THREAD

**Issue by FrankTrog** [infusionsoft/infusionsoft-php#35]
What is vendor/autoload.php supposed to be in the sample?
require_once '../vendor/autoload.php';

**Comment by micfai** [comment]
You need to run `composer install`

If you are not familiar with composer, here is a getting started guide.

https://getcomposer.org/doc/00-intro.md

**Comment by kressaty** [comment]
Frank you an also always get support at https://developer.infusionsoft.com/support/tickets/create/

We try and keep Github Issues for issue tracking of the API ;-). Good luck!

**Comment by FrankTrog** [comment]
Thanks!
