### ISSUE TITLE
Cache support

### ISSUE THREAD

**Issue by graphem** [infusionsoft/infusionsoft-php#4]
This is more a suggestion than a issue. I know that guzzle has a cache plugin. It will be great to see caching implemented in this sdk to speed up calls, as some of the call to isoft can be really time consuming and API has a rate limit. Thanks!

**Comment by kressaty** [comment]
As we're moving to using GH Issues more for actual issues, I'm going to close this out. If anyone wants to create a pull request please do so, but we've added this on the list of new features to consider in future versions of the SDK.
