### ISSUE TITLE
Legacy Token Authorization Expiration?

### ISSUE THREAD

**Issue by jwondrusch** [infusionsoft/infusionsoft-php#40]
From the docs:

> In the past, the Infusionsoft API has relied on a simple token based system; while those tokens will remain active until some date in the future, any new implementations will be required to use OAuth for all requests.

As the maintainer of a repository supporting this older method (used by many WordPress users, which only have PHP 5.2), I'd like to know:

- When will this old token based method be expiring?
- Will there be an announcement in advance of the expiration, or will you guys just flip the switch?
- Do you have a PHP 5.2 friendly wrapper for the new iSDK?

**Comment by micfai** [comment]
We do not currently have a date for when the old method will be expiring.

We will provide an announcement in advance with a decent amount of time to prepare for the switch.

We do not and are not going to have a PHP 5.2 friendly wrapper. PHP 5.2 is past end of life and is no longer supported. PHP 5.3 is also EOL and should be upgraded to 5.4 at a minimum as soon as possible (although 5.5+ is preferred).
