### ISSUE TITLE
Getting uncaught exception on requestAccessToken 

### ISSUE THREAD

**Issue by gtk-1235** [infusionsoft/infusionsoft-php#41]
so if I run the sample code (with what I assume to be proper credentials (as when I change them I get an error "Unable to create access token." on the https://signin.infusionsoft.com/app/oauth/authorize site)), 
I get a consistent exception thrown as follows.

I have created a sandbox account (and tried connecting with a production account as well) and I can't figure out what's going on here.

For clarity, this is when I click on the link to the getAuthorizationUrl, sign into my infusion sandbox account, and then the exception is thrown after I'm redirected to the proper url. I see two get parameters passed back from the login (?scope=full|tv265.infusionsoft.com&code=) where code is a 24 character alphanumeric string.

I've tried catching the exception and seeing if the token was still getting set, but alas it was not.

Any help at all is appreciated!

       Infusionsoft\Http\HttpException: exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response
       [status code] 400
       [reason phrase] Bad Request
       [url] https://api.infusionsoft.com/token' in /MYSITE/vendor/guzzle/guzzle/src/Guzzle/Http/Exception/BadResponseException.php:43

Full error:

          Fatal error: Uncaught exception 'Infusionsoft\Http\HttpException' with message 'exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message ' in EDITEDvendor/infusionsoft/php-sdk/src/Infusionsoft/Http/GuzzleClient.php on line 59 Infusionsoft\Http\HttpException: exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response [status code] 400 [reason phrase] Bad Request [url] https://api.infusionsoft.com/token' in EDITED/vendor/guzzle/guzzle/src/Guzzle/Http/Exception/BadResponseException.php:43 Stack trace: #0 EDITED/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response)) #1 [internal function]: Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 EDITED/vendor/symfony/event-dispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #3 EDITED/vendor/symfony/event-dispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\Common\Event)) #4 /EDITED/content/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(589): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('request.error', Object(Guzzle\Common\Event)) #5 /EDITED/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(378): Guzzle\Http\Message\Request->processResponse(Array) #6 EDITEDvendor/guzzle/guzzle/src/Guzzle/Http/Message/EntityEnclosingRequest.php(49): Guzzle\Http\Message\Request->setState('complete', Array) #7 EDITEDvendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(286): Guzzle\Http\Message\EntityEnclosingRequest->setState('complete', Array) #8 EDITEDvendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(244): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array) #9 EDITEDvendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(227): Guzzle\Http\Curl\CurlMulti->processMessages() #10 EDITEDvendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(211): Guzzle\Http\Curl\CurlMulti->executeHandles() #11 EDITEDvendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(105): Guzzle\Http\Curl\CurlMulti->perform() #12 EDITEDvendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMultiProxy.php(91): Guzzle\Http\Curl\CurlMulti->send() #13 EDITEDvendor/guzzle/guzzle/src/Guzzle/Http/Client.php(282): Guzzle\Http\Curl\CurlMultiProxy->send() #14 EDITEDvendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(198): Guzzle\Http\Client->send(Object(Guzzle\Http\Message\EntityEnclosingRequest)) #15 EDITEDvendor/infusionsoft/php-sdk/src/Infusionsoft/Http/GuzzleClient.php(53): Guzzle\Http\Message\Request->send() #16 EDITEDvendor/infusionsoft/php-sdk/src/Infusionsoft/Infusionsoft.php(229): Infusionsoft\Http\GuzzleClient->request('https://api.inf...', Array, Array, 'POST') #17 EDITEDControllers/manage_controller.php(119): Infusionsoft\Infusionsoft->requestAccessToken('xemv93sx32u22c3...') #18 EDITEDLibrary/Route.php(56): manage_controller->infusionSoft() #19 EDITEDLibrary/Route.php(35): loadController(Array) #20 EDITEDloader.php(31): require('/var/smartsite/...') #21 EDITEDindex.php(19): require('/var/smartsite/...') #22 {main} in EDITEDvendor/infusionsoft/php-sdk/src/Infusionsoft/Http/GuzzleClient.php on line 59 Call Stack: 0.0000 240848 1. {main}() EDITEDindex.php:0 0.0001 241368 2. require('EDITEDloader.php') EDITEDindex.php:19 0.0017 322464 3. require('EDITEDLibrary/Route.php') EDITEDloader.php:31 0.0017 323176 4. loadController() EDITEDLibrary/Route.php:35 0.0030 374696 5. manage_controller->infusionSoft() EDITEDLibrary/Route.php:56 0.0034 421464 6. Infusionsoft\Infusionsoft->requestAccessToken() EDITEDControllers/manage_controller.php:119 0.0036 433792 7. Infusionsoft\Http\GuzzleClient->request() EDITEDvendor/infusionsoft/php-sdk/src/Infusionsoft/Infusionsoft.php:229

With the following code

          $infusionsoft = new \Infusionsoft\Infusionsoft(array(
				'clientId'     => APPLICATION_KEY
				'clientSecret' => APPLICATION_CLIENT_SECRET,
				'redirectUri'  => $redirectUri,
			));

		
			// If we are returning from Infusionsoft we need to exchange the code for an
			// access token.
			if (isset($_GET['code']) and !$infusionsoft->getToken()) {
				$infusionsoft->requestAccessToken($_GET['code']);
			}

        if ($infusionsoft->getToken()) {
				die('THIS CODE HAS NEVER RUN');
			} else {
				echo '<a href="' . $infusionsoft->getAuthorizationUrl() . '">Click here to authorize</a>';
			}

**Comment by KelseySheely** [comment]
I am also seeing this error when I make the refreshAccessToken call

**Comment by gtk-1235** [comment]
This error was because because I was creating the $redirectUri from the $_SERVER['REQUEST_URI'] instead of building the url properly (or hardcoding).

**Comment by Harry003** [comment]
My redirect URI is correct. but I'm still getting this error "Unable to create access token" with options deny and allow...

**Comment by micfai** [comment]
@Harry003 that could be caused by your key is still pending approval. Submit a ticket with your ley and we can check it out.  https://developer.infusionsoft.com/support/tickets/create/

**Comment by benjaminprojas** [comment]
@micfai We have the same issue, opened a ticket but have yet to receive a reply.  We would love to get this resolved ASAP.  Is there usually a long wait for a ticket to get looked at?

Thanks!
