### ISSUE TITLE
vendor/autoload.php does not exist in the repository.

### ISSUE THREAD

**Issue by CristianEnache** [infusionsoft/infusionsoft-php#42]
Am I missing something?
require_once 'vendor/autoload.php';

**Comment by kressaty** [comment]
Ah - just run "composer update" in that directory to install the composer dependencies; the vendor directory will be created automatically. If you're unfamiliar with composer, check out a ton of info about it here: https://getcomposer.org/

**Comment by CristianEnache** [comment]
Just came back few months later and found this :D Thanks
