### ISSUE TITLE
Session token not found

### ISSUE THREAD

**Issue by reyhansofian** [infusionsoft/infusionsoft-php#43]
Hi! I'm quite new with Infusionsoft API. I'm using Laravel and I'm following [this tutorial](https://developer.infusionsoft.com/tutorials/using-the-infusionsoft-php-sdk-with-a-microframework/#exchange-the-code-for-an-access-token). I just started with **Exchange the Code for an Access Token**. And I just realized that there's no session named `token` by debugging using `$request->session('token')` after redirect back to my site and all I got is Laravel session. My code looks like this
```
public function key(Request $request)
    {
        // Setup a new Infusionsoft SDK object
        $infusionsoft = new Infusionsoft(array(
            'clientId'     => getenv('INFUSIONSOFT_CLIENT_ID'),
            'clientSecret' => getenv('INFUSIONSOFT_CLIENT_SECRET'),
            'redirectUri'  => getenv('INFUSIONSOFT_REDIRECT_URL'),
        ));

        // If the serialized token is already available in the session storage,
        // we tell the SDK to use that token for subsequent requests, rather
        // than try and retrieve another one.
        if ($request->has('token')) {
            $infusionsoft->setToken(unserialize($request->session('token')));
        }

        // If we are returning from Infusionsoft we need to exchange the code
        // for an access token.
        if ($request->has('token') and !$infusionsoft->getToken()) {
            $infusionsoft->requestAccessToken($request->get('code'));
        }

        dd($infusionsoft);
    }
```
Is there any fix for this?

**Comment by kressaty** [comment]
Long story short - it should be $request->has('code') not token, but this is the wrong repo. Can you move this issue to https://github.com/infusionsoft/api-oauth-php-lumen and we'll get that fixed and updated in the tutorial?

**Comment by reyhansofian** [comment]
@kressaty moved this issue to [here](https://github.com/infusionsoft/api-oauth-php-lumen/issues/1)
