### ISSUE TITLE
CURL <url> Malformed

### ISSUE THREAD

**Issue by merlindiavova** [infusionsoft/infusionsoft-php#47]
When using the cURL client i regularly get the following error 

Fatal error: Uncaught exception 'Amesplash\Infusionsoft\Http\HttpException' with message 'exception 'Ivory\HttpAdapter\HttpAdapterException' with message 'An error occurred when fetching the URI "/DataService.add" with the adapter "curl" ("<url> malformed").

Sometimes if i retry the query it passes. This is generally caused when using the DataService.add or DataService.Query.

Any advise on this.

**Comment by kressaty** [comment]
Merlin I don't think we've ever been able to recreate this, and with two big changes in structure since this issue, I'm going to close. Let me know if you're still having trouble.

**Comment by prashantvictory** [comment]
I am facing the same issue, and it did happened after updating infusion-php via composer, before that all was working fine. Please advise, what should I check here to fix this?
