### ISSUE TITLE
Token expired time

### ISSUE THREAD

**Issue by reyhansofian** [infusionsoft/infusionsoft-php#51]
I have following code to call Infusionsoft API

```
    public function call($method, $call, $args = array(), $count = 0)
    {
        if ($count > 10) {
            log_message('error', '10 failed tries made to: Infusionsoft->' . $method . '->' . $call . '() passing the arguments:<br/>' . print_r($args, true));
            throw new \Infusionsoft\Http\HttpException('10 failed tries made to: Infusionsoft->' . $method . '->' . $call . '() passing the arguments:<br/>' . print_r($args, true));
        }

        $this->setSettings();  // Get serialized token from database and store it to $this->infSettings

        $this->infusionsoft = new Infusionsoft(array(
            'clientId' => getenv('INFUSIONSOFT_CLIENT_ID'),
            'clientSecret' => getenv('INFUSIONSOFT_CLIENT_SECRET'),
            'redirectUri' => getenv('INFUSIONSOFT_REDIRECT_URL'),
        ));

        $token = $this->setInfToken($this->infSettings);  // Set infusionsoft token object and return the token object

        if ($token->getEndOfLife() < time()) { // Imitating Infusionsoft request() method
            $token = $this->infusionsoft->refreshAccessToken();
            log_message('error', 'Token has been refreshed <br/><pre>' . print_r($token, true) . '</pre>');

            $this->saveNewToken($token);  // Save new token to database
            log_message('error', 'New token saved');
        }

        // Try API call
        try {
            $data = $this->infusionsoft->{$method}()->{$call}(...$args);
        } catch (TokenExpiredException $ex) {
            log_message('debug', 'Token expired, refreshing token <br/><pre>' . print_r($token, true) . '</pre>');

            $token = $this->infusionsoft->refreshAccessToken();
            log_message('debug', 'Token has been refreshed <br/><pre>' . print_r($token, true) . '</pre>');

            $this->saveNewToken($token);

            $data = $this->call($method, $call, $args, ++$count);
        }

        return $data;
    }
```

with this code, when token expired, it will return "401 unauthorized" error. It seems the token didn't get refreshed although I've added token expired condition. So, I'm trying to re-authorize and Infusionsoft auth server return data with following `endOfLife`:

```php
[endOfLife] => 1446495397 // date('d-m-Y H:i:s', 1446495397) = 02-11-2015 20:16:37
```

and then, I'm trying to set it to Infusionsoft token object and debug it. Surprisingly, the token object  `endOfLife` become:

```php
[endOfLife] => 2892962011 // date('d-m-Y H:i:s', 2892962011) = 29-07-1925 02:05:15
```

That's why my token expiration checking didn't work at all. So I check this SDK, I found that on Token class constructor, it add time to the `endOfLife` element

```php
if (isset($data['expires_in']))
{
	$this->setEndOfLife(time() + $data['expires_in']);
	unset($data['expires_in']);
}
```

Is it intended or what? Because it won't meet the token expired condition.

**Comment by kressaty** [comment]
Is the time correct on your server?

**Comment by reyhansofian** [comment]
Yes @kressaty. I've confirmed it and it's correct. Nothing's wrong with my server time.

**Comment by kressaty** [comment]
Ok cool. Not knowing everything since I can't see your save method, you shouldn't need the try/catch for expiration on the method request because you're already checking for the expired token in the IF block above it. That leads me to wonder if perhaps there's a missing serialization, or the token isn't being stored in the object the same way when you manually refresh vs when you catch the exception (this would cause it to try and refresh *again*, which obviously you don't want). If you remove the second attempt to refresh, and verify that it's properly serialized/unserialized as you put/get it from storage, does it work?

**Comment by reyhansofian** [comment]
Ok. I've tried to serialized the token returned from auth server and put it on storage. And unserialized it then set it to token using `setToken()` method. It seems to work! I think there's no chance to build the token manually via  `new Token()` constructor. Since I'm casting the token object to array. Here's how I build the token manually last time

```
$infToken = new Token([
            'access_token' => $settings['token']['accessToken'],
            'refresh_token' => $settings['token']['refreshToken'],
            'expires_in' => $settings['token']['endOfLife'],
]);

$infToken->setExtraInfo($settings['token']['extraInfo']);
$this->infusionsoft->setToken($infToken);
```

I'll keep you informed in the next 8 hours!

**Comment by kressaty** [comment]
Yeah if you're deconstructing and rebuilding the token each time, you're opening up big opportunity for errors. I recommend serializing the InfusionsoftToken object straight into a string, and then deserializing it right back out again to minimize collisions.

**Comment by harshitnayak45** [comment]
I have successfully refreshed the access token. I have  to insert the contact details to infusionsoft via cron job  But i have one question Did this script successfully run and maintain the refreshing access token ? because currently i have maintain the session. please answer my question ASAP.

**Comment by reyhansofian** [comment]
@harshitnayak45 in my experience, yes it's successfully refreshing access token. FYI, I'm not in the project which is using Infusionsoft anymore.

**Comment by harshitnayak45** [comment]
I have interested the serialize token into database and set token then refresh them with the help of session.
every time a new refreshed tokens  are inserted to DB.

**Comment by reyhansofian** [comment]
please open up a new PR if you need something to ask
