### ISSUE TITLE
Not able to update custom drop down field values with data()->update method

### ISSUE THREAD

**Issue by davellan** [infusionsoft/infusionsoft-php#60]
I am trying to update the values of a custom drop down field using the API, but regardless of what I try to pass, nothing changes.

`$infusionsoft->data()->update('DataFormField',$recordID,array('values'=>$newValues));`

Where **$recordID** is an integer, and **$newValues** is a string with \r\n separated values _(as IFS API returns when queried)._

When I run this call, it returns successful _(returning the recordID)_, but the values do not change. I tried then using $newValues as an array instead of string and same result. Tried searching online but can't seem to find any documentation on how to update the custom fields online through the API.

**Comment by micfai** [comment]
I checked my tests and you have to use DataService.updateCustomField.

```php
    $Id = 4;
    $values = ['Values' => ['Test 1', 'Test 2', 'Test 3']];
    $updatedField = $infusionsoft->data()->updateCustomField($Id, $values);
```

**Comment by davellan** [comment]
Ahh, I did not see that on the docs last I checked, good to know! 

Still not working for me though. :(

**Method Call:**

> <methodCall>

	<methodName>DataService.updateCustomField</methodName>
	<params>
		<param>
			<value>
				<string>##############</string>
			</value>
		</param>
		<param>
			<value>
				<int>83</int>
			</value>
		</param>
		<param>
			<value>
				<struct>
					<member>
						<name>Values</name>
						<value>
							<array>
								<data>
									<value>
										<string>Walk In</string>
									</value>
									<value>
										<string>Call</string>
									</value>
									<value>
										<string>Internet</string>
									</value>
									<value>
										<string>Live Chat*</string>
									</value>
								</data>
							</array>
						</value>
					</member>
				</struct>
			</value>
		</param>
	</params>
</methodCall>

**Method Response:**

> <methodResponse>

	<params>
		<param>
			<value>
				<boolean>1</boolean>
			</value>
		</param>
	</params>
</methodResponse>

**Comment by davellan** [comment]
Figured it out.

The drop down values have to be a string. So it needed to be formatted like this:

`   $Id = 4;
    $values = ['Values' => 'Test 1\r\nTest 2\r\nTest 3'];
    $updatedField = $infusionsoft->data()->updateCustomField($Id, $values);`

Once I did that it worked.
