### ISSUE TITLE
Unable to select all recipients in template created via API

### ISSUE THREAD

**Issue by shainanand** [infusionsoft/infusionsoft-php#62]
I added a template via API to the InfusionSoft account. But I am unable to send it to all the contacts in my account. How can I set the **To** address to all contacts via API?

**Comment by kressaty** [comment]
Did you ever figure this out?

**Comment by shainanand** [comment]
Not yet

**Comment by kressaty** [comment]
Did you file a support ticket on the developer portal? https://developer.infusionsoft.com/support/tickets/create/

**Comment by kressaty** [comment]
Closing due to no response and no verification of error in lib.
