### ISSUE TITLE
Custom Drop down fields updated through the API do not update on campaign builder decision diamonds

### ISSUE THREAD

**Issue by davellan** [infusionsoft/infusionsoft-php#63]
Suppose you have a custom drop down field with the values: _ValueA,ValueB,ValueC._

You then use this field in a decision diamond in the campaign builder, and select the different values for different sequences.

Using the **API to update the custom fields** (using _updateCustomField_), you change the values of this custom field to: _First,Second,Third._

**Now if you go into the campaign with the decision diamond, it will still show the old values as valid options, and NOT show the new values.** The decision diamond will also be broken, as no one will be able to attain these values.

However, **if you just go to the admin settings and save the custom field values without changing anything**, and then go back into the campaign, it will show that the old values (_ValueA,ValueB,Valuec_) are invalid, and allow you to choose the new values.

This makes using the updateCustomField a big deterrent, because of the obvious complications this causes. I have tested this a few times and the result is consistent.

**Comment by micfai** [comment]
This isn't an SDK issue. Please submit a case on this. https://developer.infusionsoft.com/support/tickets/create/
