### ISSUE TITLE
Any reason why the CreditCardSubmissionService is not in this library?

### ISSUE THREAD

**Issue by graphem** [infusionsoft/infusionsoft-php#66]
We are trying to implement a api payment processing without being PCI compliant and sees the CreditCardSubmissionService is the way to go, but seems it been left out of this library. Any reason?

**Comment by AustinTBiggs** [comment]
I'm going to go ahead and bump this, I'm also curious.

**Comment by jasonlam604** [comment]
Bump, I'm curious as well, thank you

**Comment by micfai** [comment]
This has been addressed in the 1.3.0-beta release.
