### ISSUE TITLE
Getting fatal GuzzleHttpClient error when authenticating

### ISSUE THREAD

**Issue by kevdotbadger** [infusionsoft/infusionsoft-php#67]
hello, I'm running through the docs on https://github.com/infusionsoft/infusionsoft-php#authentication and I instantly get a  

   Fatal error: Declaration of Infusionsoft\Http\GuzzleHttpClient::request() must be compatible with GuzzleHttp\ClientInterface::request($method, $uri = NULL, array $options = Array) in /var/www/scotchbox2.dev/public/infusionsoft/vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/GuzzleHttpClient.php on line 15

using scotchbox which runs PHP 5.6.10-1+deb.sury.org~trusty+1

**Comment by kressaty** [comment]
I hate to ask dumb questions, but can you confirm composer is updated to latest?

**Comment by mallenuk** [comment]
I had the same issue today. The declaration of GuzzleHttp\ClientInterface::request() contains a default value of NULL on the $url parameter. This is missing from the Infusionsoft code and is causing the crash. I added the default NULL value and my code was working again. Obviously not great as changing the code of the library.

**Comment by kressaty** [comment]
What version of Guzzle is being loaded @mallenuk?

**Comment by mallenuk** [comment]
@kressaty, sorry forgot to mention that. Guzzle 6.2.0 is being loaded. The InfusionPHP composer.json has the tilde on it's Guzzle dependency so loads the latest stable release. I am using InfusionPHP version 1.2.0

**Comment by kressaty** [comment]
@mallenuk awesome thanks. looking into what changed; we may need to be stricter about what version of guzzle we require. will ping you back.

**Comment by micfai** [comment]
Give v1.2.1 a try. This had already been fixed form PR #56 however it wasn't ever added to a release.

**Comment by mallenuk** [comment]
@micfai that tag worked for me, thanks!

**Comment by kressaty** [comment]
Closing; fixed in latest release.
