### ISSUE TITLE
README file instructions for Lumen do not work

### ISSUE THREAD

**Issue by dctucker** [infusionsoft/infusionsoft-php#68]
Specifically this line:

 $data = app('infusionsoft')->query("Contact",1000,0,['Id' => '123'],['Id','FirstName','LastName','Email']);

I get "undefined method 'query'" when attempting this.

**Comment by kressaty** [comment]
Can you please provide which versions of lumen, guzzle, and the library you're using?

**Comment by cliftonscott** [comment]
I'm seeing this error too using the latest version of the SDK.

**Comment by cliftonscott** [comment]
I see it's because the README is incorrect.
