### ISSUE TITLE
Lumen support library does not work, array keys for $config are wrong

### ISSUE THREAD

**Issue by dctucker** [infusionsoft/infusionsoft-php#69]
The keys in the register() function of InfusionServiceProvider for Lumen are snake_case while the receiving constructor of Infusionsoft expects camelCase.

client_id in ServiceProvider, constructor expects clientId.

This is silly, please amend.

**Comment by kressaty** [comment]
d3b2a2ca6a31815d013ef6a26cc981b1a08def1b

**Comment by micfai** [comment]
Release v1.2.2 addresses this.
