### ISSUE TITLE
Getting access token with developer account

### ISSUE THREAD

**Issue by jonatas-ns** [infusionsoft/infusionsoft-php#71]
Hello.

Im trying to develop an application that integrates Facebook and Infusionsoft.
I have a developer account which gives me an api key, secret and app name.

When I try to get the access token using OAuth, I am asked to login, but I don't have any account to login and get an access token.

How developers can get an temporary access token to build an application, create fake lists, fake contacts and then, when all gets done, call real users with real Infusionsoft account to use the application?

@micfai @kressaty can you please help on that?

**Comment by kressaty** [comment]
Request a sandbox application :-)  

https://developer.infusionsoft.com/resources/sandbox-application/

**Comment by jonatas-ns** [comment]
Thanks! :dancer:

**Comment by n3rio** [comment]
Hi, i already request and got a sandbox application, but i would like to know how to connect my app to the sandbox app using OAUTH, can you help me with that?

**Comment by esraa00** [comment]
did you create it n3rio?
