### ISSUE TITLE
How to use this library with direct access

### ISSUE THREAD

**Issue by matthebs** [infusionsoft/infusionsoft-php#72]
I have direct access to the infusionsoft account, I'm not building a third party service so there is no reason to log in to get authorization, Is there anyway to get the access token in infusionsoft somehow?

I used the very old api a long time ago 4 years ago. But thought it might be nice to use this one.

**Comment by kressaty** [comment]
Unfortunately this library does not include a way to use the legacy API tokens. You can, however, use a tool like this https://www.runscope.com/oauth2_tool to generate an access token, and then just use the refresh method in the SDK to continuously refresh the token. Many people end up stashing an "authorize" URL somewhere in their app so they can reauth whenever necessary as well.
