### ISSUE TITLE
guzzle-promises update is breaking build

### ISSUE THREAD

**Issue by drewbix** [infusionsoft/infusionsoft-php#74]
Ran composer update today and started getting this error:

Type error: Argument 1 passed to fXmlRpc\Transport\HttpAdapterTransport::__construc t() must be an instance of Http\Message\MessageFactory, instance of Ivory\HttpAdapter\Guzzle6HttpAdapter given, called in /home/vagrant/funneldash/vendor/infusionsoft/php-sdk/src/Infusionsoft/Http/GuzzleHttpClient.php on line 42

which I think is due to guzzlehttp/promises upgrading from 1.1 to 1.2. Maybe need to lock down a specific version of guzzle instead of ~6.0 ?

**Comment by kressaty** [comment]
Mmmm probably. Will look at this ASAP; does it work when you revert to a previous version of guzzle?

**Comment by drewbix** [comment]
Yea when I revert my composer.lock and run composer install again everything works fine.

**Comment by gomako** [comment]
Hi, am running into this issue and am a bit confused. Which composer.lock file do you change? The one in the sdk or the root project one?

**Comment by kressaty** [comment]
@drewbix @gomako @micfai  I've pushed a new branch that fixes this in my testing, care to give it a whirl before I merge and release? hotfix/fxmlrpc-version

**Comment by kressaty** [comment]
For the record - seems to be the xmlrpc lib, not guzzle on its own. We'll upgrade to the newest of both, but I want to get this released to avoid other issues in the meantime.

**Comment by Spoowy** [comment]
https://github.com/infusionsoft/infusionsoft-php/issues/75#issuecomment-222115383

I have added a quick fix here for those who want to get it done.

**Comment by kressaty** [comment]
Updated in latest release, sorry for the delay!
