### ISSUE TITLE
README Incorrect. Lumen Service Provider

### ISSUE THREAD

**Issue by cliftonscott** [infusionsoft/infusionsoft-php#82]
`$data = app('infusionsoft')->query("Contact",1000,0,['Id' => '123'],['Id','FirstName','LastName','Email'], 'Id', false);`

Should be
`$data = app('infusionsoft')->data->query("Contact",1000,0,['Id' => '123'],['Id','FirstName','LastName','Email'], 'Id', false);`

**Comment by micfai** [comment]
Fixed with a2197e66f92db53a9238f9324f31b7d998c39450
