### ISSUE TITLE
Running tests on php7

### ISSUE THREAD

**Issue by yugenekr** [infusionsoft/infusionsoft-php#84]
Hello,

I was getting this error when running tests using php 7.0.8 : 
```
PHP Fatal error:  Redefinition of parameter $_ in vendor/lisachenko/go-aop-php/src/Go/Aop/Pointcut/PointcutGrammar.php on line 61
```
After some research it became clear this is due to codeception/aspect-mock library current version and loaded packages that don't support php7.

I've required ```"codeception/aspect-mock": "~2.0.0"```  locally, php7 support specific issues were gone.
I also had to update ```/tests/bootstrap.php```  (due to ```codeception/aspect-mock/README.md```)

```
$kernel->init([
	'debug'        => true,
	'includePaths' => [__DIR__.'/../src'],
	'excludePaths' => [__DIR__.'/../']
]);
```

With these updates tests finally run.

But, there're two error results, that I'm not **that** need/willing to look into this time and not sure if it's libs update related or something else. **Please let me know if there're known fixes to these errors or someone finds resolution to them too**. Thanks!

```
1) Infusionsoft\Api\InvoiceServiceTest::testCreateBlankOrder
Exception: Class fXmlRpc\Transport\GuzzleBridge not loaded.
If you want to test undefined class use 'test::spec' method

/vendor/codeception/aspect-mock/src/AspectMock/Test.php:98
/tests/ServiceTest.php:36

2) Infusionsoft\InfusionsoftTest::testRequestingAccessTokenSetsAccessToken
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0_Infusionsoft_Http_GuzzleHttpClient::request('POST', 'https://api.infusionsoft.com/token', ['body' => 'client_id=foo&client_secret=bar&code=code&grant_type=authorization_code&redirect_uri=baz', 'headers' => [...]]). Either the method was unexpected or its arguments matched no expected argument list for this method

/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:92
/src/Infusionsoft/Infusionsoft.php:234
/tests/Infusionsoft/InfusionsoftTest.php:134 
```

**Comment by micfai** [comment]
We're working on a revamp of all the tests. If you check the develop branch it has passing tests.

**Comment by yugenekr** [comment]
I see. Thanks.
