### ISSUE TITLE
REST Orders API Date String 

### ISSUE THREAD

**Issue by arvenom** [infusionsoft/infusionsoft-php#87]
When querying the REST Orders API by Date range 

```
 $this->infusionsoft->orders()->where('since', '2013-10-09T16:15:24.000-07:00')
```
I get the exception  

```
GuzzleHttp\Exception\ClientException: Client error: `GET https://api.infusionsoft.com/crm/rest/v1/orders?access_token=TOKEN&limit=2&since=2016-10-09T16%3A15%3A24-07%3A00` resulted in a `400 Bad Request` response:
```

So I assume the Date Parser on the Infusionsoft does not url decode the string which guzzle however transforms in the GET request. ```2016-10-09T16%3A15%3A24-07%3A00```

**Comment by micfai** [comment]
The Date Format is different between your where clause and the exception. In the exception it's missing the micro seconds.

`2013-10-09T16:15:24.000-07:00`
vs
`2016-10-09T16:15:24-07:00`

**Comment by arvenom** [comment]
Sorry totally oversaw that, thanks! :)
