### ISSUE TITLE
addToCampaign not working

### ISSUE THREAD

**Issue by chasevorn** [infusionsoft/infusionsoft-php#88]
I'm trying to add a contactID to a campaign ($infusionsoft->contacts()->addToCampaign($contactId, $campaignId))
and I'm getting this error:

> Fatal error: Uncaught exception 'Infusionsoft\Http\HttpException' with message 'exception 'fXmlRpc\Exception\FaultException' with message '[Loading]Error loading follow-up sequence' in

I've double checked if the campaign id and contact id are correct. Don't know what else to do

**Comment by manu144x** [comment]
I had this issue to, the idea is that you have create an API entry point in the campaign, assign a name to it, and use that to inject users. 
It killed me too :)

https://developer.infusionsoft.com/docs/xml-rpc/#funnel-achieve-a-goal

**Comment by micfai** [comment]
@chasevorn addToCampaign is adding a contact to a legacy follow-up sequence, not to the campaign builder. See @manu144x comment for adding to a campaign builder campaign.
