### ISSUE TITLE
OAuth not working as it should

### ISSUE THREAD

**Issue by mrizwan47** [infusionsoft/infusionsoft-php#90]
I used the example code. Everything works well redirected me to authorization page and two buttons shows up "Deny" and "Allow". No matter what I choose it redirects me back to:

`http://example.com/redirectURL?state=&error_description=User+denied+access+to+resource&error=access_denied&error_uri=https%3A%2F%2Fdeveloper.infusionsoft.com%2Fdocs%2Fread%2FGetting_Started_With_OAuth2`

Cleared cookies, tried another browser. Still the same :disappointed: 

It this because my redirect url is password protected (in case infusionsoft sends cURL sort of request instead of browser redirect)?

**Comment by micfai** [comment]
This can be caused by not having an Infusionsoft application attached to your Infusionsoft Id. Have you gotten one of our [sandboxes](https://developer.infusionsoft.com/resources/sandbox-application/)?

**Comment by mrizwan47** [comment]
No, it's a developer account. [Here](https://keys.developer.infusionsoft.com/apps/mykeys)

**Comment by mrizwan47** [comment]
And for OAuth, I am using standard account (after login it takes me [here](https://signin.infusionsoft.com/app/central/home) )

**Comment by mrizwan47** [comment]
I just signed up through the sandbox link you posted. After billing a mail came "Set up your Infusionsoft Account". I clicked the link and continued the form, it says you already have account.

**Comment by micfai** [comment]
@mrizwan47 When you click the link from the email, on the page there is a link that says "Already have an account?". Click that link and then login with your existing credentials.

**Comment by mrizwan47** [comment]
@micfai Thanks, it solved the problem.
