### ISSUE TITLE
Invoice createBlankOrder not working

### ISSUE THREAD

**Issue by cipl-sheik** [infusionsoft/infusionsoft-php#92]
Hi, I am using this API while creating the invoice i am getting the below issue. Please help me to come out from this issue.

![localhost sheik infusionsoft php master contact_test php](https://cloud.githubusercontent.com/assets/17022464/20146323/76fd72ca-a6c9-11e6-9903-a91812523795.png)

`Code Used :
$contactID = $userInfo[0]['Id'];
    $name = $userInfo[0]['FirstName'];
    $orderDate = date('Ymd\TH:i:s');
    $leadAffiliateID = 2;
    $saleAffiliateID = 2;
    $invoiceID = $infusionsoft->invoices->createBlankOrder($contactID, $name, $orderDate, $leadAffiliateID, $saleAffiliateID);`

**Comment by yugenekr** [comment]
Try matching parameters data types according to: https://developer.infusionsoft.com/docs/xml-rpc/#invoice-create-an-invoice . First of all I'd typecast $contactID to integer in your case.

**Comment by cipl-sheik** [comment]
Thanks for the reply. But same data i passed as statically that time also i getting same issue.

I am sharing my code again added with int type. 

Dynamic view:
==========
$contactID = (int)$userInfo[0]['Id'];
    $name = $userInfo[0]['FirstName'];
    $orderDate = date('Ymd\TH:i:s');
    $leadAffiliateID = 2;
    $saleAffiliateID = 2;
    $invoiceID = $infusionsoft->invoices->createBlankOrder($contactID, $name, $orderDate, $leadAffiliateID, $saleAffiliateID);

Static Inputs : (Same issue for static inputs)
=========
$invoiceID = $infusionsoft->invoices->createBlankOrder(3, 'Test Invoice', '20080908T00:00:00', 2, 2);

**Comment by micfai** [comment]
You need to use a DateTime object not a DateTime string.  https://github.com/infusionsoft/infusionsoft-php#dates

**Comment by cipl-sheik** [comment]
Yes thanks for the help :-). I used same format mentioned in API docs but anyway it get fixed but still have issues with invoice -> addManualPayment serverice. I think this service also i used different type of format. 
If you are able to figure out why this not creating the payment.

Syntex:
=====
$infusionsoft->invoices->addManualPayment($invoiceID, $amount, $date, $paymentType, $description, $bypassCommissions);

Static :
=====
$infusionsoft->invoices->addManualPayment(35, 50, new \DateTime($date), 'Credit Card', 'Test Payment', 0);

**Comment by cipl-sheik** [comment]
I fixed it by adding addOrderItem and correct payment type. Thanks
