### ISSUE TITLE
Mimic Form Submission?

### ISSUE THREAD

**Issue by MACscr** [infusionsoft/infusionsoft-php#94]
I have a form that a client gave me that they want to run in their app, but the system is specifically setup to work with api's because it stores the data locally in their db and then every 5 minutes or so, processes that data and send it to whatever api they are using. Right now with the infusionsoft api, I see no way to submit that data through REST or xml-rpc. Seems we can only retrieve forms through the api. Am I missing something? With other systems I simply need a list id and an api key and then obviously a list of fields/data that I want to submit.

**Comment by micfai** [comment]
Currently there is no way to submit a form through the api. You have to submit it to the form action url.

If you are trying to add/update contacts then you can use the xmlrpc contact service.  https://developer.infusionsoft.com/docs/xml-rpc/#contact
