### ISSUE TITLE
Unable to get user Information

### ISSUE THREAD

**Issue by rabnawazPikesSoft** [infusionsoft/infusionsoft-php#95]
The user who authenicate with my infusion api and after getting access token and refresesh token how i get user email or any unique key to identify on my site that user id or key is register again that user 

if is there any way kindly answer me thanks

**Comment by micfai** [comment]
@rabnawazPikesSoft Take a look at DataService.getUserInfo

https://github.com/infusionsoft/infusionsoft-php/blob/master/src/Infusionsoft/Api/DataService.php#L152

**Comment by rabnawazPikesSoft** [comment]
as far i know it is that data we add in contact of my account isnt it like that ?

**Comment by micfai** [comment]
This is what that endpoint returns. There are no parameters needed.

```
{
	"displayName": "Test Tester",
	"appUrl": "https://APPNAME.infusionsoft.com",
	"globalUserId": "123",
	"localUserId": "1",
	"casUsername": "test@example.com",
	"appAlias": "APPNAME"
}
```

**Comment by rabnawazPikesSoft** [comment]
thanks

On Sat, Dec 10, 2016 at 1:57 AM, Michael Fairchild <notifications@github.com
