### ISSUE TITLE
Using API without OAuth for guest visitors

### ISSUE THREAD

**Issue by pwaring** [infusionsoft/infusionsoft-php#98]
I have a client who wants to have a web form which captures data from site visitors and creates contacts under the client's InfusionSoft account - effectively using it as a data store.

The site visitors won't have an InfusionSoft account and therefore won't be able to authorise the client's application, so OAuth doesn't really make sense. Is there any way to work around this? The documentation suggests that it's possible to use the XML-RPC API using tokens, but this is only possible 'until some date in the future'. I don't want to build something which suddenly stops working in a few months because it relies on functionality which is going to be removed.

**Comment by KelseySheely** [comment]
While I agree that OAuth doesn't quite make sense in your case, the fact is that Infusionsoft is phasing out the legacy API Key authentication and OAuth will soon be the only option. I would recommend using it for any and all future development.  

The way you do that in your case is to set up an authorization page as shown in the docs which will be authenticated by your client one time. Then you can store the token in a database and use it for all the calls that should be triggered by visitors.

**Comment by pwaring** [comment]
Closing as no official response - end solution was to submit to an InfusionSoft form instead of using the API.
